// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: search/search.proto

package searchv1

import (
	common "github.com/market-4-test/contract-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchEntity int32

const (
	SearchEntity_SEARCH_ENTITY_UNSPECIFIED SearchEntity = 0
	SearchEntity_PRODUCT                   SearchEntity = 1
	SearchEntity_CATEGORY                  SearchEntity = 2
	SearchEntity_TAG                       SearchEntity = 3
)

// Enum value maps for SearchEntity.
var (
	SearchEntity_name = map[int32]string{
		0: "SEARCH_ENTITY_UNSPECIFIED",
		1: "PRODUCT",
		2: "CATEGORY",
		3: "TAG",
	}
	SearchEntity_value = map[string]int32{
		"SEARCH_ENTITY_UNSPECIFIED": 0,
		"PRODUCT":                   1,
		"CATEGORY":                  2,
		"TAG":                       3,
	}
)

func (x SearchEntity) Enum() *SearchEntity {
	p := new(SearchEntity)
	*p = x
	return p
}

func (x SearchEntity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchEntity) Descriptor() protoreflect.EnumDescriptor {
	return file_search_search_proto_enumTypes[0].Descriptor()
}

func (SearchEntity) Type() protoreflect.EnumType {
	return &file_search_search_proto_enumTypes[0]
}

func (x SearchEntity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchEntity.Descriptor instead.
func (SearchEntity) EnumDescriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{0}
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityType    SearchEntity           `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3,enum=search.SearchEntity" json:"entity_type,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetEntityType() SearchEntity {
	if x != nil {
		return x.EntityType
	}
	return SearchEntity_SEARCH_ENTITY_UNSPECIFIED
}

func (x *Entity) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Entity) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Entity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpsertEntityParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityType    SearchEntity           `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3,enum=search.SearchEntity" json:"entity_type,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEntityParams) Reset() {
	*x = UpsertEntityParams{}
	mi := &file_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEntityParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEntityParams) ProtoMessage() {}

func (x *UpsertEntityParams) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEntityParams.ProtoReflect.Descriptor instead.
func (*UpsertEntityParams) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertEntityParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpsertEntityParams) GetEntityType() SearchEntity {
	if x != nil {
		return x.EntityType
	}
	return SearchEntity_SEARCH_ENTITY_UNSPECIFIED
}

func (x *UpsertEntityParams) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpsertEntityParams) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetEntitiesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Type          *SearchEntity          `protobuf:"varint,4,opt,name=type,proto3,enum=search.SearchEntity,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitiesParams) Reset() {
	*x = GetEntitiesParams{}
	mi := &file_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitiesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitiesParams) ProtoMessage() {}

func (x *GetEntitiesParams) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitiesParams.ProtoReflect.Descriptor instead.
func (*GetEntitiesParams) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntitiesParams) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetEntitiesParams) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetEntitiesParams) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetEntitiesParams) GetType() SearchEntity {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return SearchEntity_SEARCH_ENTITY_UNSPECIFIED
}

type GetEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitiesResponse) Reset() {
	*x = GetEntitiesResponse{}
	mi := &file_search_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitiesResponse) ProtoMessage() {}

func (x *GetEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitiesResponse.ProtoReflect.Descriptor instead.
func (*GetEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{3}
}

func (x *GetEntitiesResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type SetActiveEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityType    SearchEntity           `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3,enum=search.SearchEntity" json:"entity_type,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveEntity) Reset() {
	*x = SetActiveEntity{}
	mi := &file_search_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveEntity) ProtoMessage() {}

func (x *SetActiveEntity) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveEntity.ProtoReflect.Descriptor instead.
func (*SetActiveEntity) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{4}
}

func (x *SetActiveEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetActiveEntity) GetEntityType() SearchEntity {
	if x != nil {
		return x.EntityType
	}
	return SearchEntity_SEARCH_ENTITY_UNSPECIFIED
}

func (x *SetActiveEntity) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type SetActiveEntitiesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *SetActiveEntity       `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveEntitiesParams) Reset() {
	*x = SetActiveEntitiesParams{}
	mi := &file_search_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveEntitiesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveEntitiesParams) ProtoMessage() {}

func (x *SetActiveEntitiesParams) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveEntitiesParams.ProtoReflect.Descriptor instead.
func (*SetActiveEntitiesParams) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{5}
}

func (x *SetActiveEntitiesParams) GetList() *SetActiveEntity {
	if x != nil {
		return x.List
	}
	return nil
}

var File_search_search_proto protoreflect.FileDescriptor

const file_search_search_proto_rawDesc = "" +
	"\n" +
	"\x13search/search.proto\x12\x06search\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\ventity_type\x18\x02 \x01(\x0e2\x14.search.SearchEntityR\n" +
	"entityType\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8c\x01\n" +
	"\x12UpsertEntityParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\ventity_type\x18\x02 \x01(\x0e2\x14.search.SearchEntityR\n" +
	"entityType\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"\x8f\x01\n" +
	"\x11GetEntitiesParams\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.search.SearchEntityH\x00R\x04type\x88\x01\x01B\a\n" +
	"\x05_type\"A\n" +
	"\x13GetEntitiesResponse\x12*\n" +
	"\bentities\x18\x01 \x03(\v2\x0e.search.EntityR\bentities\"u\n" +
	"\x0fSetActiveEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\ventity_type\x18\x02 \x01(\x0e2\x14.search.SearchEntityR\n" +
	"entityType\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\"F\n" +
	"\x17SetActiveEntitiesParams\x12+\n" +
	"\x04list\x18\x01 \x01(\v2\x17.search.SetActiveEntityR\x04list*Q\n" +
	"\fSearchEntity\x12\x1d\n" +
	"\x19SEARCH_ENTITY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPRODUCT\x10\x01\x12\f\n" +
	"\bCATEGORY\x10\x02\x12\a\n" +
	"\x03TAG\x10\x032\xdf\x01\n" +
	"\x06Search\x12E\n" +
	"\vGetEntities\x12\x19.search.GetEntitiesParams\x1a\x1b.search.GetEntitiesResponse\x12H\n" +
	"\x0eUpsertEntities\x12\x19.search.GetEntitiesParams\x1a\x1b.search.GetEntitiesResponse\x12D\n" +
	"\x11SetActiveEntities\x12\x1f.search.SetActiveEntitiesParams\x1a\x0e.common.StatusB6Z4github.com/market-4-test/contract-go/search;searchv1b\x06proto3"

var (
	file_search_search_proto_rawDescOnce sync.Once
	file_search_search_proto_rawDescData []byte
)

func file_search_search_proto_rawDescGZIP() []byte {
	file_search_search_proto_rawDescOnce.Do(func() {
		file_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_search_proto_rawDesc), len(file_search_search_proto_rawDesc)))
	})
	return file_search_search_proto_rawDescData
}

var file_search_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_search_search_proto_goTypes = []any{
	(SearchEntity)(0),               // 0: search.SearchEntity
	(*Entity)(nil),                  // 1: search.Entity
	(*UpsertEntityParams)(nil),      // 2: search.UpsertEntityParams
	(*GetEntitiesParams)(nil),       // 3: search.GetEntitiesParams
	(*GetEntitiesResponse)(nil),     // 4: search.GetEntitiesResponse
	(*SetActiveEntity)(nil),         // 5: search.SetActiveEntity
	(*SetActiveEntitiesParams)(nil), // 6: search.SetActiveEntitiesParams
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
	(*common.Status)(nil),           // 8: common.Status
}
var file_search_search_proto_depIdxs = []int32{
	0,  // 0: search.Entity.entity_type:type_name -> search.SearchEntity
	7,  // 1: search.Entity.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: search.UpsertEntityParams.entity_type:type_name -> search.SearchEntity
	0,  // 3: search.GetEntitiesParams.type:type_name -> search.SearchEntity
	1,  // 4: search.GetEntitiesResponse.entities:type_name -> search.Entity
	0,  // 5: search.SetActiveEntity.entity_type:type_name -> search.SearchEntity
	5,  // 6: search.SetActiveEntitiesParams.list:type_name -> search.SetActiveEntity
	3,  // 7: search.Search.GetEntities:input_type -> search.GetEntitiesParams
	3,  // 8: search.Search.UpsertEntities:input_type -> search.GetEntitiesParams
	6,  // 9: search.Search.SetActiveEntities:input_type -> search.SetActiveEntitiesParams
	4,  // 10: search.Search.GetEntities:output_type -> search.GetEntitiesResponse
	4,  // 11: search.Search.UpsertEntities:output_type -> search.GetEntitiesResponse
	8,  // 12: search.Search.SetActiveEntities:output_type -> common.Status
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_search_search_proto_init() }
func file_search_search_proto_init() {
	if File_search_search_proto != nil {
		return
	}
	file_search_search_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_search_proto_rawDesc), len(file_search_search_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_search_proto_goTypes,
		DependencyIndexes: file_search_search_proto_depIdxs,
		EnumInfos:         file_search_search_proto_enumTypes,
		MessageInfos:      file_search_search_proto_msgTypes,
	}.Build()
	File_search_search_proto = out.File
	file_search_search_proto_goTypes = nil
	file_search_search_proto_depIdxs = nil
}
