// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: catalog/brands.proto

package catalogv1

import (
	common "github.com/market-4-test/contract-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Brand struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug     string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	IsActive bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// optional bytes image_uuid = 5;
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Brand) Reset() {
	*x = Brand{}
	mi := &file_catalog_brands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Brand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Brand) ProtoMessage() {}

func (x *Brand) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Brand.ProtoReflect.Descriptor instead.
func (*Brand) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{0}
}

func (x *Brand) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Brand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Brand) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Brand) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Brand) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Brand) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BrandShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandShort) Reset() {
	*x = BrandShort{}
	mi := &file_catalog_brands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandShort) ProtoMessage() {}

func (x *BrandShort) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandShort.ProtoReflect.Descriptor instead.
func (*BrandShort) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{1}
}

func (x *BrandShort) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrandShort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrandShort) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type UpsertBrandParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"` //  optional bytes image_uuid = 5;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertBrandParams) Reset() {
	*x = UpsertBrandParams{}
	mi := &file_catalog_brands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertBrandParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertBrandParams) ProtoMessage() {}

func (x *UpsertBrandParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertBrandParams.ProtoReflect.Descriptor instead.
func (*UpsertBrandParams) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertBrandParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertBrandParams) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpsertBrandParams) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateBrandParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UpsertBrandParams     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBrandParams) Reset() {
	*x = CreateBrandParams{}
	mi := &file_catalog_brands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBrandParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBrandParams) ProtoMessage() {}

func (x *CreateBrandParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBrandParams.ProtoReflect.Descriptor instead.
func (*CreateBrandParams) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBrandParams) GetData() *UpsertBrandParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateBrandParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *UpsertBrandParams     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBrandParams) Reset() {
	*x = UpdateBrandParams{}
	mi := &file_catalog_brands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBrandParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBrandParams) ProtoMessage() {}

func (x *UpdateBrandParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBrandParams.ProtoReflect.Descriptor instead.
func (*UpdateBrandParams) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBrandParams) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBrandParams) GetData() *UpsertBrandParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateActiveToBrands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActiveToBrands) Reset() {
	*x = UpdateActiveToBrands{}
	mi := &file_catalog_brands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActiveToBrands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActiveToBrands) ProtoMessage() {}

func (x *UpdateActiveToBrands) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActiveToBrands.ProtoReflect.Descriptor instead.
func (*UpdateActiveToBrands) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateActiveToBrands) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *UpdateActiveToBrands) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetBrandsPaginateParams struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Params        *common.GetPaginateParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrandsPaginateParams) Reset() {
	*x = GetBrandsPaginateParams{}
	mi := &file_catalog_brands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrandsPaginateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandsPaginateParams) ProtoMessage() {}

func (x *GetBrandsPaginateParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandsPaginateParams.ProtoReflect.Descriptor instead.
func (*GetBrandsPaginateParams) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{6}
}

func (x *GetBrandsPaginateParams) GetParams() *common.GetPaginateParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type GetBrandsPaginateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Brand               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Meta          *common.PaginateMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrandsPaginateResponse) Reset() {
	*x = GetBrandsPaginateResponse{}
	mi := &file_catalog_brands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrandsPaginateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandsPaginateResponse) ProtoMessage() {}

func (x *GetBrandsPaginateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandsPaginateResponse.ProtoReflect.Descriptor instead.
func (*GetBrandsPaginateResponse) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{7}
}

func (x *GetBrandsPaginateResponse) GetList() []*Brand {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetBrandsPaginateResponse) GetMeta() *common.PaginateMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetBrandsShortPaginateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*BrandShort          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Meta          *common.PaginateMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrandsShortPaginateResponse) Reset() {
	*x = GetBrandsShortPaginateResponse{}
	mi := &file_catalog_brands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrandsShortPaginateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandsShortPaginateResponse) ProtoMessage() {}

func (x *GetBrandsShortPaginateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandsShortPaginateResponse.ProtoReflect.Descriptor instead.
func (*GetBrandsShortPaginateResponse) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{8}
}

func (x *GetBrandsShortPaginateResponse) GetList() []*BrandShort {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetBrandsShortPaginateResponse) GetMeta() *common.PaginateMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetOffsetBrandsParams struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Params        *common.GetOffsetParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetBrandsParams) Reset() {
	*x = GetOffsetBrandsParams{}
	mi := &file_catalog_brands_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetBrandsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetBrandsParams) ProtoMessage() {}

func (x *GetOffsetBrandsParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetBrandsParams.ProtoReflect.Descriptor instead.
func (*GetOffsetBrandsParams) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{9}
}

func (x *GetOffsetBrandsParams) GetParams() *common.GetOffsetParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type GetOffsetBrandsShortParams struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Params        *common.GetOffsetParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetBrandsShortParams) Reset() {
	*x = GetOffsetBrandsShortParams{}
	mi := &file_catalog_brands_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetBrandsShortParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetBrandsShortParams) ProtoMessage() {}

func (x *GetOffsetBrandsShortParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetBrandsShortParams.ProtoReflect.Descriptor instead.
func (*GetOffsetBrandsShortParams) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{10}
}

func (x *GetOffsetBrandsShortParams) GetParams() *common.GetOffsetParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type GetBrandsOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Brand               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrandsOffsetResponse) Reset() {
	*x = GetBrandsOffsetResponse{}
	mi := &file_catalog_brands_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrandsOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandsOffsetResponse) ProtoMessage() {}

func (x *GetBrandsOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandsOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetBrandsOffsetResponse) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{11}
}

func (x *GetBrandsOffsetResponse) GetList() []*Brand {
	if x != nil {
		return x.List
	}
	return nil
}

type GetBrandsShortOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*BrandShort          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrandsShortOffsetResponse) Reset() {
	*x = GetBrandsShortOffsetResponse{}
	mi := &file_catalog_brands_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrandsShortOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandsShortOffsetResponse) ProtoMessage() {}

func (x *GetBrandsShortOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandsShortOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetBrandsShortOffsetResponse) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{12}
}

func (x *GetBrandsShortOffsetResponse) GetList() []*BrandShort {
	if x != nil {
		return x.List
	}
	return nil
}

type GetBrandByIdParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrandByIdParams) Reset() {
	*x = GetBrandByIdParams{}
	mi := &file_catalog_brands_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrandByIdParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandByIdParams) ProtoMessage() {}

func (x *GetBrandByIdParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandByIdParams.ProtoReflect.Descriptor instead.
func (*GetBrandByIdParams) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{13}
}

func (x *GetBrandByIdParams) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StatusBrand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusBrand) Reset() {
	*x = StatusBrand{}
	mi := &file_catalog_brands_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusBrand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusBrand) ProtoMessage() {}

func (x *StatusBrand) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusBrand.ProtoReflect.Descriptor instead.
func (*StatusBrand) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{14}
}

func (x *StatusBrand) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatusBrand) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DeleteBrandsParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBrandsParams) Reset() {
	*x = DeleteBrandsParams{}
	mi := &file_catalog_brands_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBrandsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBrandsParams) ProtoMessage() {}

func (x *DeleteBrandsParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBrandsParams.ProtoReflect.Descriptor instead.
func (*DeleteBrandsParams) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteBrandsParams) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteBrandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *StatusBrand           `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBrandsResponse) Reset() {
	*x = DeleteBrandsResponse{}
	mi := &file_catalog_brands_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBrandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBrandsResponse) ProtoMessage() {}

func (x *DeleteBrandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_brands_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBrandsResponse.ProtoReflect.Descriptor instead.
func (*DeleteBrandsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_brands_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteBrandsResponse) GetList() *StatusBrand {
	if x != nil {
		return x.List
	}
	return nil
}

var File_catalog_brands_proto protoreflect.FileDescriptor

const file_catalog_brands_proto_rawDesc = "" +
	"\n" +
	"\x14catalog/brands.proto\x12\acatalog\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x01\n" +
	"\x05Brand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"D\n" +
	"\n" +
	"BrandShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"X\n" +
	"\x11UpsertBrandParams\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"C\n" +
	"\x11CreateBrandParams\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.catalog.UpsertBrandParamsR\x04data\"S\n" +
	"\x11UpdateBrandParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12.\n" +
	"\x04data\x18\x02 \x01(\v2\x1a.catalog.UpsertBrandParamsR\x04data\"E\n" +
	"\x14UpdateActiveToBrands\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\"L\n" +
	"\x17GetBrandsPaginateParams\x121\n" +
	"\x06params\x18\x01 \x01(\v2\x19.common.GetPaginateParamsR\x06params\"i\n" +
	"\x19GetBrandsPaginateResponse\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.catalog.BrandR\x04list\x12(\n" +
	"\x04meta\x18\x02 \x01(\v2\x14.common.PaginateMetaR\x04meta\"s\n" +
	"\x1eGetBrandsShortPaginateResponse\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.catalog.BrandShortR\x04list\x12(\n" +
	"\x04meta\x18\x02 \x01(\v2\x14.common.PaginateMetaR\x04meta\"H\n" +
	"\x15GetOffsetBrandsParams\x12/\n" +
	"\x06params\x18\x01 \x01(\v2\x17.common.GetOffsetParamsR\x06params\"M\n" +
	"\x1aGetOffsetBrandsShortParams\x12/\n" +
	"\x06params\x18\x01 \x01(\v2\x17.common.GetOffsetParamsR\x06params\"=\n" +
	"\x17GetBrandsOffsetResponse\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.catalog.BrandR\x04list\"G\n" +
	"\x1cGetBrandsShortOffsetResponse\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.catalog.BrandShortR\x04list\"$\n" +
	"\x12GetBrandByIdParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"5\n" +
	"\vStatusBrand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"&\n" +
	"\x12DeleteBrandsParams\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"@\n" +
	"\x14DeleteBrandsResponse\x12(\n" +
	"\x04list\x18\x01 \x01(\v2\x14.catalog.StatusBrandR\x04listB8Z6github.com/market-4-test/contract-go/catalog;catalogv1b\x06proto3"

var (
	file_catalog_brands_proto_rawDescOnce sync.Once
	file_catalog_brands_proto_rawDescData []byte
)

func file_catalog_brands_proto_rawDescGZIP() []byte {
	file_catalog_brands_proto_rawDescOnce.Do(func() {
		file_catalog_brands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_brands_proto_rawDesc), len(file_catalog_brands_proto_rawDesc)))
	})
	return file_catalog_brands_proto_rawDescData
}

var file_catalog_brands_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_catalog_brands_proto_goTypes = []any{
	(*Brand)(nil),                          // 0: catalog.Brand
	(*BrandShort)(nil),                     // 1: catalog.BrandShort
	(*UpsertBrandParams)(nil),              // 2: catalog.UpsertBrandParams
	(*CreateBrandParams)(nil),              // 3: catalog.CreateBrandParams
	(*UpdateBrandParams)(nil),              // 4: catalog.UpdateBrandParams
	(*UpdateActiveToBrands)(nil),           // 5: catalog.UpdateActiveToBrands
	(*GetBrandsPaginateParams)(nil),        // 6: catalog.GetBrandsPaginateParams
	(*GetBrandsPaginateResponse)(nil),      // 7: catalog.GetBrandsPaginateResponse
	(*GetBrandsShortPaginateResponse)(nil), // 8: catalog.GetBrandsShortPaginateResponse
	(*GetOffsetBrandsParams)(nil),          // 9: catalog.GetOffsetBrandsParams
	(*GetOffsetBrandsShortParams)(nil),     // 10: catalog.GetOffsetBrandsShortParams
	(*GetBrandsOffsetResponse)(nil),        // 11: catalog.GetBrandsOffsetResponse
	(*GetBrandsShortOffsetResponse)(nil),   // 12: catalog.GetBrandsShortOffsetResponse
	(*GetBrandByIdParams)(nil),             // 13: catalog.GetBrandByIdParams
	(*StatusBrand)(nil),                    // 14: catalog.StatusBrand
	(*DeleteBrandsParams)(nil),             // 15: catalog.DeleteBrandsParams
	(*DeleteBrandsResponse)(nil),           // 16: catalog.DeleteBrandsResponse
	(*timestamppb.Timestamp)(nil),          // 17: google.protobuf.Timestamp
	(*common.GetPaginateParams)(nil),       // 18: common.GetPaginateParams
	(*common.PaginateMeta)(nil),            // 19: common.PaginateMeta
	(*common.GetOffsetParams)(nil),         // 20: common.GetOffsetParams
}
var file_catalog_brands_proto_depIdxs = []int32{
	17, // 0: catalog.Brand.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: catalog.Brand.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: catalog.CreateBrandParams.data:type_name -> catalog.UpsertBrandParams
	2,  // 3: catalog.UpdateBrandParams.data:type_name -> catalog.UpsertBrandParams
	18, // 4: catalog.GetBrandsPaginateParams.params:type_name -> common.GetPaginateParams
	0,  // 5: catalog.GetBrandsPaginateResponse.list:type_name -> catalog.Brand
	19, // 6: catalog.GetBrandsPaginateResponse.meta:type_name -> common.PaginateMeta
	1,  // 7: catalog.GetBrandsShortPaginateResponse.list:type_name -> catalog.BrandShort
	19, // 8: catalog.GetBrandsShortPaginateResponse.meta:type_name -> common.PaginateMeta
	20, // 9: catalog.GetOffsetBrandsParams.params:type_name -> common.GetOffsetParams
	20, // 10: catalog.GetOffsetBrandsShortParams.params:type_name -> common.GetOffsetParams
	0,  // 11: catalog.GetBrandsOffsetResponse.list:type_name -> catalog.Brand
	1,  // 12: catalog.GetBrandsShortOffsetResponse.list:type_name -> catalog.BrandShort
	14, // 13: catalog.DeleteBrandsResponse.list:type_name -> catalog.StatusBrand
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_catalog_brands_proto_init() }
func file_catalog_brands_proto_init() {
	if File_catalog_brands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_brands_proto_rawDesc), len(file_catalog_brands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_brands_proto_goTypes,
		DependencyIndexes: file_catalog_brands_proto_depIdxs,
		MessageInfos:      file_catalog_brands_proto_msgTypes,
	}.Build()
	File_catalog_brands_proto = out.File
	file_catalog_brands_proto_goTypes = nil
	file_catalog_brands_proto_depIdxs = nil
}
