// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: catalog/catalog.proto

package catalogv1

import (
	common "github.com/market-4-test/contract-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_catalog_catalog_proto protoreflect.FileDescriptor

const file_catalog_catalog_proto_rawDesc = "" +
	"\n" +
	"\x15catalog/catalog.proto\x12\acatalog\x1a\x13common/common.proto\x1a\x16catalog/products.proto\x1a\x18catalog/categories.proto\x1a\x12catalog/tags.proto\x1a\x14catalog/brands.proto2\xec\x1d\n" +
	"\aCatalog\x12S\n" +
	"\x0fGetTagsPaginate\x12\x1e.catalog.GetTagsPaginateParams\x1a .catalog.GetTagsPaginateResponse\x12b\n" +
	"\x14GetTagsShortPaginate\x12#.catalog.GetTagsShortPaginateParams\x1a%.catalog.GetTagsShortPaginateResponse\x12M\n" +
	"\rGetTagsOffset\x12\x1c.catalog.GetTagsOffsetParams\x1a\x1e.catalog.GetTagsOffsetResponse\x12\\\n" +
	"\x12GetTagsShortOffset\x12!.catalog.GetTagsShortOffsetParams\x1a#.catalog.GetTagsShortOffsetResponse\x125\n" +
	"\n" +
	"GetTagById\x12\x19.catalog.GetTagByIdParams\x1a\f.catalog.Tag\x123\n" +
	"\tCreateTag\x12\x18.catalog.CreateTagParams\x1a\f.catalog.Tag\x123\n" +
	"\tUpdateTag\x12\x18.catalog.UpdateTagParams\x1a\f.catalog.Tag\x12D\n" +
	"\n" +
	"DeleteTags\x12\x19.catalog.DeleteTagsParams\x1a\x1b.catalog.DeleteTagsResponse\x12h\n" +
	"\x16CheckAvailableTagNames\x12%.catalog.CheckAvailableTagNamesParams\x1a'.catalog.CheckAvailableTagNamesResponse\x12Y\n" +
	"\x11GetBrandsPaginate\x12 .catalog.GetBrandsPaginateParams\x1a\".catalog.GetBrandsPaginateResponse\x12c\n" +
	"\x16GetBrandsShortPaginate\x12 .catalog.GetBrandsPaginateParams\x1a'.catalog.GetBrandsShortPaginateResponse\x12S\n" +
	"\x0fGetBrandsOffset\x12\x1e.catalog.GetOffsetBrandsParams\x1a .catalog.GetBrandsOffsetResponse\x12b\n" +
	"\x14GetBrandsShortOffset\x12#.catalog.GetOffsetBrandsShortParams\x1a%.catalog.GetBrandsShortOffsetResponse\x12;\n" +
	"\fGetBrandById\x12\x1b.catalog.GetBrandByIdParams\x1a\x0e.catalog.Brand\x12E\n" +
	"\x11GetBrandShortById\x12\x1b.catalog.GetBrandByIdParams\x1a\x13.catalog.BrandShort\x129\n" +
	"\vCreateBrand\x12\x1a.catalog.CreateBrandParams\x1a\x0e.catalog.Brand\x129\n" +
	"\vUpdateBrand\x12\x1a.catalog.UpdateBrandParams\x1a\x0e.catalog.Brand\x12J\n" +
	"\fDeleteBrands\x12\x1b.catalog.DeleteBrandsParams\x1a\x1d.catalog.DeleteBrandsResponse\x12e\n" +
	"\x15GetCategoriesPaginate\x12$.catalog.GetCategoriesPaginateParams\x1a&.catalog.GetCategoriesPaginateResponse\x12o\n" +
	"\x1aGetCategoriesShortPaginate\x12$.catalog.GetCategoriesPaginateParams\x1a+.catalog.GetCategoriesShortPaginateResponse\x12_\n" +
	"\x13GetCategoriesOffset\x12\".catalog.GetCategoriesOffsetParams\x1a$.catalog.GetCategoriesOffsetResponse\x12n\n" +
	"\x18GetCategoriesShortOffset\x12'.catalog.GetCategoriesShortOffsetParams\x1a).catalog.GetCategoriesShortOffsetResponse\x12D\n" +
	"\x0fGetCategoryById\x12\x1e.catalog.GetCategoryByIdParams\x1a\x11.catalog.Category\x12N\n" +
	"\x14GetCategoryShortById\x12\x1e.catalog.GetCategoryByIdParams\x1a\x16.catalog.CategoryShort\x12B\n" +
	"\x0eCreateCategory\x12\x1d.catalog.CreateCategoryParams\x1a\x11.catalog.Category\x12B\n" +
	"\x0eUpdateCategory\x12\x1d.catalog.UpdateCategoryParams\x1a\x11.catalog.Category\x12V\n" +
	"\x10DeleteCategories\x12\x1f.catalog.DeleteCategoriesParams\x1a!.catalog.DeleteCategoriesResponse\x12G\n" +
	"\x12SetImageToCategory\x12!.catalog.SetImageToCategoryParams\x1a\x0e.common.Status\x12w\n" +
	"\x1bUpdateOrderSortToCategories\x12*.catalog.UpdateOrderSortToCategoriesParams\x1a,.catalog.UpdateOrderSortToCategoriesResponse\x12O\n" +
	"\x1aCheckCategoryAvailableSlug\x12!.catalog.CheckAvailableSlugParams\x1a\x0e.common.Status\x12_\n" +
	"\x13GetProductsPaginate\x12\".catalog.GetProductsPaginateParams\x1a$.catalog.GetProductsPaginateResponse\x12n\n" +
	"\x18GetProductsShortPaginate\x12'.catalog.GetProductsShortPaginateParams\x1a).catalog.GetProductsShortPaginateResponse\x12Y\n" +
	"\x11GetProductsOffset\x12 .catalog.GetProductsOffsetParams\x1a\".catalog.GetProductsOffsetResponse\x12h\n" +
	"\x16GetProductsShortOffset\x12%.catalog.GetProductsShortOffsetParams\x1a'.catalog.GetProductsShortOffsetResponse\x12U\n" +
	"\x12GetProductsByUuids\x12!.catalog.GetProductsByUuidsParams\x1a\x1c.catalog.GetProductsResponse\x12E\n" +
	"\x10GetProductByUuid\x12\x1f.catalog.GetProductByUuidParams\x1a\x10.catalog.Product\x12?\n" +
	"\rCreateProduct\x12\x1c.catalog.CreateProductParams\x1a\x10.catalog.Product\x12C\n" +
	"\rUpdateProduct\x12 .catalog.UpdateProductMetaParams\x1a\x10.catalog.Product\x12I\n" +
	"\x13UpdateProductStatus\x12\".catalog.UpdateProductStatusParams\x1a\x0e.common.Status\x12b\n" +
	"\x14UpdateProductsStocks\x12#.catalog.UpdateProductsStocksParams\x1a%.catalog.UpdateProductsStocksResponse\x12b\n" +
	"\x14UpdateProductsPrices\x12#.catalog.UpdateProductsPricesParams\x1a%.catalog.UpdateProductsPricesResponse\x12U\n" +
	"\x19CheckProductAvailableSlug\x12(.catalog.CheckProductAvailableSlugParams\x1a\x0e.common.Status\x12_\n" +
	"\x1eToggleAttachProductsToCategory\x12-.catalog.ToggleAttachProductsToCategoryParams\x1a\x0e.common.Status\x12[\n" +
	"\x1cToggleAttachProductsToBrands\x12+.catalog.ToggleAttachProductsToBrandsParams\x1a\x0e.common.Status\x12W\n" +
	"\x1aToggleAttachProductsToTags\x12).catalog.ToggleAttachProductsToTagsParams\x1a\x0e.common.StatusB8Z6github.com/market-4-test/contract-go/catalog;catalogv1b\x06proto3"

var file_catalog_catalog_proto_goTypes = []any{
	(*GetTagsPaginateParams)(nil),                // 0: catalog.GetTagsPaginateParams
	(*GetTagsShortPaginateParams)(nil),           // 1: catalog.GetTagsShortPaginateParams
	(*GetTagsOffsetParams)(nil),                  // 2: catalog.GetTagsOffsetParams
	(*GetTagsShortOffsetParams)(nil),             // 3: catalog.GetTagsShortOffsetParams
	(*GetTagByIdParams)(nil),                     // 4: catalog.GetTagByIdParams
	(*CreateTagParams)(nil),                      // 5: catalog.CreateTagParams
	(*UpdateTagParams)(nil),                      // 6: catalog.UpdateTagParams
	(*DeleteTagsParams)(nil),                     // 7: catalog.DeleteTagsParams
	(*CheckAvailableTagNamesParams)(nil),         // 8: catalog.CheckAvailableTagNamesParams
	(*GetBrandsPaginateParams)(nil),              // 9: catalog.GetBrandsPaginateParams
	(*GetOffsetBrandsParams)(nil),                // 10: catalog.GetOffsetBrandsParams
	(*GetOffsetBrandsShortParams)(nil),           // 11: catalog.GetOffsetBrandsShortParams
	(*GetBrandByIdParams)(nil),                   // 12: catalog.GetBrandByIdParams
	(*CreateBrandParams)(nil),                    // 13: catalog.CreateBrandParams
	(*UpdateBrandParams)(nil),                    // 14: catalog.UpdateBrandParams
	(*DeleteBrandsParams)(nil),                   // 15: catalog.DeleteBrandsParams
	(*GetCategoriesPaginateParams)(nil),          // 16: catalog.GetCategoriesPaginateParams
	(*GetCategoriesOffsetParams)(nil),            // 17: catalog.GetCategoriesOffsetParams
	(*GetCategoriesShortOffsetParams)(nil),       // 18: catalog.GetCategoriesShortOffsetParams
	(*GetCategoryByIdParams)(nil),                // 19: catalog.GetCategoryByIdParams
	(*CreateCategoryParams)(nil),                 // 20: catalog.CreateCategoryParams
	(*UpdateCategoryParams)(nil),                 // 21: catalog.UpdateCategoryParams
	(*DeleteCategoriesParams)(nil),               // 22: catalog.DeleteCategoriesParams
	(*SetImageToCategoryParams)(nil),             // 23: catalog.SetImageToCategoryParams
	(*UpdateOrderSortToCategoriesParams)(nil),    // 24: catalog.UpdateOrderSortToCategoriesParams
	(*CheckAvailableSlugParams)(nil),             // 25: catalog.CheckAvailableSlugParams
	(*GetProductsPaginateParams)(nil),            // 26: catalog.GetProductsPaginateParams
	(*GetProductsShortPaginateParams)(nil),       // 27: catalog.GetProductsShortPaginateParams
	(*GetProductsOffsetParams)(nil),              // 28: catalog.GetProductsOffsetParams
	(*GetProductsShortOffsetParams)(nil),         // 29: catalog.GetProductsShortOffsetParams
	(*GetProductsByUuidsParams)(nil),             // 30: catalog.GetProductsByUuidsParams
	(*GetProductByUuidParams)(nil),               // 31: catalog.GetProductByUuidParams
	(*CreateProductParams)(nil),                  // 32: catalog.CreateProductParams
	(*UpdateProductMetaParams)(nil),              // 33: catalog.UpdateProductMetaParams
	(*UpdateProductStatusParams)(nil),            // 34: catalog.UpdateProductStatusParams
	(*UpdateProductsStocksParams)(nil),           // 35: catalog.UpdateProductsStocksParams
	(*UpdateProductsPricesParams)(nil),           // 36: catalog.UpdateProductsPricesParams
	(*CheckProductAvailableSlugParams)(nil),      // 37: catalog.CheckProductAvailableSlugParams
	(*ToggleAttachProductsToCategoryParams)(nil), // 38: catalog.ToggleAttachProductsToCategoryParams
	(*ToggleAttachProductsToBrandsParams)(nil),   // 39: catalog.ToggleAttachProductsToBrandsParams
	(*ToggleAttachProductsToTagsParams)(nil),     // 40: catalog.ToggleAttachProductsToTagsParams
	(*GetTagsPaginateResponse)(nil),              // 41: catalog.GetTagsPaginateResponse
	(*GetTagsShortPaginateResponse)(nil),         // 42: catalog.GetTagsShortPaginateResponse
	(*GetTagsOffsetResponse)(nil),                // 43: catalog.GetTagsOffsetResponse
	(*GetTagsShortOffsetResponse)(nil),           // 44: catalog.GetTagsShortOffsetResponse
	(*Tag)(nil),                                  // 45: catalog.Tag
	(*DeleteTagsResponse)(nil),                   // 46: catalog.DeleteTagsResponse
	(*CheckAvailableTagNamesResponse)(nil),       // 47: catalog.CheckAvailableTagNamesResponse
	(*GetBrandsPaginateResponse)(nil),            // 48: catalog.GetBrandsPaginateResponse
	(*GetBrandsShortPaginateResponse)(nil),       // 49: catalog.GetBrandsShortPaginateResponse
	(*GetBrandsOffsetResponse)(nil),              // 50: catalog.GetBrandsOffsetResponse
	(*GetBrandsShortOffsetResponse)(nil),         // 51: catalog.GetBrandsShortOffsetResponse
	(*Brand)(nil),                                // 52: catalog.Brand
	(*BrandShort)(nil),                           // 53: catalog.BrandShort
	(*DeleteBrandsResponse)(nil),                 // 54: catalog.DeleteBrandsResponse
	(*GetCategoriesPaginateResponse)(nil),        // 55: catalog.GetCategoriesPaginateResponse
	(*GetCategoriesShortPaginateResponse)(nil),   // 56: catalog.GetCategoriesShortPaginateResponse
	(*GetCategoriesOffsetResponse)(nil),          // 57: catalog.GetCategoriesOffsetResponse
	(*GetCategoriesShortOffsetResponse)(nil),     // 58: catalog.GetCategoriesShortOffsetResponse
	(*Category)(nil),                             // 59: catalog.Category
	(*CategoryShort)(nil),                        // 60: catalog.CategoryShort
	(*DeleteCategoriesResponse)(nil),             // 61: catalog.DeleteCategoriesResponse
	(*common.Status)(nil),                        // 62: common.Status
	(*UpdateOrderSortToCategoriesResponse)(nil),  // 63: catalog.UpdateOrderSortToCategoriesResponse
	(*GetProductsPaginateResponse)(nil),          // 64: catalog.GetProductsPaginateResponse
	(*GetProductsShortPaginateResponse)(nil),     // 65: catalog.GetProductsShortPaginateResponse
	(*GetProductsOffsetResponse)(nil),            // 66: catalog.GetProductsOffsetResponse
	(*GetProductsShortOffsetResponse)(nil),       // 67: catalog.GetProductsShortOffsetResponse
	(*GetProductsResponse)(nil),                  // 68: catalog.GetProductsResponse
	(*Product)(nil),                              // 69: catalog.Product
	(*UpdateProductsStocksResponse)(nil),         // 70: catalog.UpdateProductsStocksResponse
	(*UpdateProductsPricesResponse)(nil),         // 71: catalog.UpdateProductsPricesResponse
}
var file_catalog_catalog_proto_depIdxs = []int32{
	0,  // 0: catalog.Catalog.GetTagsPaginate:input_type -> catalog.GetTagsPaginateParams
	1,  // 1: catalog.Catalog.GetTagsShortPaginate:input_type -> catalog.GetTagsShortPaginateParams
	2,  // 2: catalog.Catalog.GetTagsOffset:input_type -> catalog.GetTagsOffsetParams
	3,  // 3: catalog.Catalog.GetTagsShortOffset:input_type -> catalog.GetTagsShortOffsetParams
	4,  // 4: catalog.Catalog.GetTagById:input_type -> catalog.GetTagByIdParams
	5,  // 5: catalog.Catalog.CreateTag:input_type -> catalog.CreateTagParams
	6,  // 6: catalog.Catalog.UpdateTag:input_type -> catalog.UpdateTagParams
	7,  // 7: catalog.Catalog.DeleteTags:input_type -> catalog.DeleteTagsParams
	8,  // 8: catalog.Catalog.CheckAvailableTagNames:input_type -> catalog.CheckAvailableTagNamesParams
	9,  // 9: catalog.Catalog.GetBrandsPaginate:input_type -> catalog.GetBrandsPaginateParams
	9,  // 10: catalog.Catalog.GetBrandsShortPaginate:input_type -> catalog.GetBrandsPaginateParams
	10, // 11: catalog.Catalog.GetBrandsOffset:input_type -> catalog.GetOffsetBrandsParams
	11, // 12: catalog.Catalog.GetBrandsShortOffset:input_type -> catalog.GetOffsetBrandsShortParams
	12, // 13: catalog.Catalog.GetBrandById:input_type -> catalog.GetBrandByIdParams
	12, // 14: catalog.Catalog.GetBrandShortById:input_type -> catalog.GetBrandByIdParams
	13, // 15: catalog.Catalog.CreateBrand:input_type -> catalog.CreateBrandParams
	14, // 16: catalog.Catalog.UpdateBrand:input_type -> catalog.UpdateBrandParams
	15, // 17: catalog.Catalog.DeleteBrands:input_type -> catalog.DeleteBrandsParams
	16, // 18: catalog.Catalog.GetCategoriesPaginate:input_type -> catalog.GetCategoriesPaginateParams
	16, // 19: catalog.Catalog.GetCategoriesShortPaginate:input_type -> catalog.GetCategoriesPaginateParams
	17, // 20: catalog.Catalog.GetCategoriesOffset:input_type -> catalog.GetCategoriesOffsetParams
	18, // 21: catalog.Catalog.GetCategoriesShortOffset:input_type -> catalog.GetCategoriesShortOffsetParams
	19, // 22: catalog.Catalog.GetCategoryById:input_type -> catalog.GetCategoryByIdParams
	19, // 23: catalog.Catalog.GetCategoryShortById:input_type -> catalog.GetCategoryByIdParams
	20, // 24: catalog.Catalog.CreateCategory:input_type -> catalog.CreateCategoryParams
	21, // 25: catalog.Catalog.UpdateCategory:input_type -> catalog.UpdateCategoryParams
	22, // 26: catalog.Catalog.DeleteCategories:input_type -> catalog.DeleteCategoriesParams
	23, // 27: catalog.Catalog.SetImageToCategory:input_type -> catalog.SetImageToCategoryParams
	24, // 28: catalog.Catalog.UpdateOrderSortToCategories:input_type -> catalog.UpdateOrderSortToCategoriesParams
	25, // 29: catalog.Catalog.CheckCategoryAvailableSlug:input_type -> catalog.CheckAvailableSlugParams
	26, // 30: catalog.Catalog.GetProductsPaginate:input_type -> catalog.GetProductsPaginateParams
	27, // 31: catalog.Catalog.GetProductsShortPaginate:input_type -> catalog.GetProductsShortPaginateParams
	28, // 32: catalog.Catalog.GetProductsOffset:input_type -> catalog.GetProductsOffsetParams
	29, // 33: catalog.Catalog.GetProductsShortOffset:input_type -> catalog.GetProductsShortOffsetParams
	30, // 34: catalog.Catalog.GetProductsByUuids:input_type -> catalog.GetProductsByUuidsParams
	31, // 35: catalog.Catalog.GetProductByUuid:input_type -> catalog.GetProductByUuidParams
	32, // 36: catalog.Catalog.CreateProduct:input_type -> catalog.CreateProductParams
	33, // 37: catalog.Catalog.UpdateProduct:input_type -> catalog.UpdateProductMetaParams
	34, // 38: catalog.Catalog.UpdateProductStatus:input_type -> catalog.UpdateProductStatusParams
	35, // 39: catalog.Catalog.UpdateProductsStocks:input_type -> catalog.UpdateProductsStocksParams
	36, // 40: catalog.Catalog.UpdateProductsPrices:input_type -> catalog.UpdateProductsPricesParams
	37, // 41: catalog.Catalog.CheckProductAvailableSlug:input_type -> catalog.CheckProductAvailableSlugParams
	38, // 42: catalog.Catalog.ToggleAttachProductsToCategory:input_type -> catalog.ToggleAttachProductsToCategoryParams
	39, // 43: catalog.Catalog.ToggleAttachProductsToBrands:input_type -> catalog.ToggleAttachProductsToBrandsParams
	40, // 44: catalog.Catalog.ToggleAttachProductsToTags:input_type -> catalog.ToggleAttachProductsToTagsParams
	41, // 45: catalog.Catalog.GetTagsPaginate:output_type -> catalog.GetTagsPaginateResponse
	42, // 46: catalog.Catalog.GetTagsShortPaginate:output_type -> catalog.GetTagsShortPaginateResponse
	43, // 47: catalog.Catalog.GetTagsOffset:output_type -> catalog.GetTagsOffsetResponse
	44, // 48: catalog.Catalog.GetTagsShortOffset:output_type -> catalog.GetTagsShortOffsetResponse
	45, // 49: catalog.Catalog.GetTagById:output_type -> catalog.Tag
	45, // 50: catalog.Catalog.CreateTag:output_type -> catalog.Tag
	45, // 51: catalog.Catalog.UpdateTag:output_type -> catalog.Tag
	46, // 52: catalog.Catalog.DeleteTags:output_type -> catalog.DeleteTagsResponse
	47, // 53: catalog.Catalog.CheckAvailableTagNames:output_type -> catalog.CheckAvailableTagNamesResponse
	48, // 54: catalog.Catalog.GetBrandsPaginate:output_type -> catalog.GetBrandsPaginateResponse
	49, // 55: catalog.Catalog.GetBrandsShortPaginate:output_type -> catalog.GetBrandsShortPaginateResponse
	50, // 56: catalog.Catalog.GetBrandsOffset:output_type -> catalog.GetBrandsOffsetResponse
	51, // 57: catalog.Catalog.GetBrandsShortOffset:output_type -> catalog.GetBrandsShortOffsetResponse
	52, // 58: catalog.Catalog.GetBrandById:output_type -> catalog.Brand
	53, // 59: catalog.Catalog.GetBrandShortById:output_type -> catalog.BrandShort
	52, // 60: catalog.Catalog.CreateBrand:output_type -> catalog.Brand
	52, // 61: catalog.Catalog.UpdateBrand:output_type -> catalog.Brand
	54, // 62: catalog.Catalog.DeleteBrands:output_type -> catalog.DeleteBrandsResponse
	55, // 63: catalog.Catalog.GetCategoriesPaginate:output_type -> catalog.GetCategoriesPaginateResponse
	56, // 64: catalog.Catalog.GetCategoriesShortPaginate:output_type -> catalog.GetCategoriesShortPaginateResponse
	57, // 65: catalog.Catalog.GetCategoriesOffset:output_type -> catalog.GetCategoriesOffsetResponse
	58, // 66: catalog.Catalog.GetCategoriesShortOffset:output_type -> catalog.GetCategoriesShortOffsetResponse
	59, // 67: catalog.Catalog.GetCategoryById:output_type -> catalog.Category
	60, // 68: catalog.Catalog.GetCategoryShortById:output_type -> catalog.CategoryShort
	59, // 69: catalog.Catalog.CreateCategory:output_type -> catalog.Category
	59, // 70: catalog.Catalog.UpdateCategory:output_type -> catalog.Category
	61, // 71: catalog.Catalog.DeleteCategories:output_type -> catalog.DeleteCategoriesResponse
	62, // 72: catalog.Catalog.SetImageToCategory:output_type -> common.Status
	63, // 73: catalog.Catalog.UpdateOrderSortToCategories:output_type -> catalog.UpdateOrderSortToCategoriesResponse
	62, // 74: catalog.Catalog.CheckCategoryAvailableSlug:output_type -> common.Status
	64, // 75: catalog.Catalog.GetProductsPaginate:output_type -> catalog.GetProductsPaginateResponse
	65, // 76: catalog.Catalog.GetProductsShortPaginate:output_type -> catalog.GetProductsShortPaginateResponse
	66, // 77: catalog.Catalog.GetProductsOffset:output_type -> catalog.GetProductsOffsetResponse
	67, // 78: catalog.Catalog.GetProductsShortOffset:output_type -> catalog.GetProductsShortOffsetResponse
	68, // 79: catalog.Catalog.GetProductsByUuids:output_type -> catalog.GetProductsResponse
	69, // 80: catalog.Catalog.GetProductByUuid:output_type -> catalog.Product
	69, // 81: catalog.Catalog.CreateProduct:output_type -> catalog.Product
	69, // 82: catalog.Catalog.UpdateProduct:output_type -> catalog.Product
	62, // 83: catalog.Catalog.UpdateProductStatus:output_type -> common.Status
	70, // 84: catalog.Catalog.UpdateProductsStocks:output_type -> catalog.UpdateProductsStocksResponse
	71, // 85: catalog.Catalog.UpdateProductsPrices:output_type -> catalog.UpdateProductsPricesResponse
	62, // 86: catalog.Catalog.CheckProductAvailableSlug:output_type -> common.Status
	62, // 87: catalog.Catalog.ToggleAttachProductsToCategory:output_type -> common.Status
	62, // 88: catalog.Catalog.ToggleAttachProductsToBrands:output_type -> common.Status
	62, // 89: catalog.Catalog.ToggleAttachProductsToTags:output_type -> common.Status
	45, // [45:90] is the sub-list for method output_type
	0,  // [0:45] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_catalog_proto_init() }
func file_catalog_catalog_proto_init() {
	if File_catalog_catalog_proto != nil {
		return
	}
	file_catalog_products_proto_init()
	file_catalog_categories_proto_init()
	file_catalog_tags_proto_init()
	file_catalog_brands_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_catalog_proto_rawDesc), len(file_catalog_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_catalog_proto_depIdxs,
	}.Build()
	File_catalog_catalog_proto = out.File
	file_catalog_catalog_proto_goTypes = nil
	file_catalog_catalog_proto_depIdxs = nil
}
