// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: catalog/categories.proto

package catalogv1

import (
	common "github.com/market-4-test/contract-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      *int32                 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	OrderSort     int32                  `protobuf:"varint,6,opt,name=order_sort,json=orderSort,proto3" json:"order_sort,omitempty"`
	ImageUuid     []byte                 `protobuf:"bytes,7,opt,name=image_uuid,json=imageUuid,proto3,oneof" json:"image_uuid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_catalog_categories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetParentId() int32 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Category) GetOrderSort() int32 {
	if x != nil {
		return x.OrderSort
	}
	return 0
}

func (x *Category) GetImageUuid() []byte {
	if x != nil {
		return x.ImageUuid
	}
	return nil
}

func (x *Category) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Category) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CategoryShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	ImageUuid     []byte                 `protobuf:"bytes,4,opt,name=image_uuid,json=imageUuid,proto3,oneof" json:"image_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryShort) Reset() {
	*x = CategoryShort{}
	mi := &file_catalog_categories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryShort) ProtoMessage() {}

func (x *CategoryShort) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryShort.ProtoReflect.Descriptor instead.
func (*CategoryShort) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryShort) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryShort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryShort) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CategoryShort) GetImageUuid() []byte {
	if x != nil {
		return x.ImageUuid
	}
	return nil
}

type UpsertCategoryParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      *int32                 `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ImageUuid     []byte                 `protobuf:"bytes,5,opt,name=image_uuid,json=imageUuid,proto3,oneof" json:"image_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertCategoryParams) Reset() {
	*x = UpsertCategoryParams{}
	mi := &file_catalog_categories_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertCategoryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCategoryParams) ProtoMessage() {}

func (x *UpsertCategoryParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCategoryParams.ProtoReflect.Descriptor instead.
func (*UpsertCategoryParams) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertCategoryParams) GetParentId() int32 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *UpsertCategoryParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertCategoryParams) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpsertCategoryParams) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpsertCategoryParams) GetImageUuid() []byte {
	if x != nil {
		return x.ImageUuid
	}
	return nil
}

type CreateCategoryParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UpsertCategoryParams  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryParams) Reset() {
	*x = CreateCategoryParams{}
	mi := &file_catalog_categories_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryParams) ProtoMessage() {}

func (x *CreateCategoryParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryParams.ProtoReflect.Descriptor instead.
func (*CreateCategoryParams) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCategoryParams) GetData() *UpsertCategoryParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateCategoryParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *UpsertCategoryParams  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryParams) Reset() {
	*x = UpdateCategoryParams{}
	mi := &file_catalog_categories_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryParams) ProtoMessage() {}

func (x *UpdateCategoryParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryParams.ProtoReflect.Descriptor instead.
func (*UpdateCategoryParams) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCategoryParams) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryParams) GetData() *UpsertCategoryParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateActiveToCategories struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActiveToCategories) Reset() {
	*x = UpdateActiveToCategories{}
	mi := &file_catalog_categories_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActiveToCategories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActiveToCategories) ProtoMessage() {}

func (x *UpdateActiveToCategories) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActiveToCategories.ProtoReflect.Descriptor instead.
func (*UpdateActiveToCategories) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateActiveToCategories) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *UpdateActiveToCategories) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateParentToCategories struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubIds        [][]byte               `protobuf:"bytes,1,rep,name=sub_ids,json=subIds,proto3" json:"sub_ids,omitempty"`
	ParentIds     []byte                 `protobuf:"bytes,2,opt,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParentToCategories) Reset() {
	*x = UpdateParentToCategories{}
	mi := &file_catalog_categories_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParentToCategories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParentToCategories) ProtoMessage() {}

func (x *UpdateParentToCategories) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParentToCategories.ProtoReflect.Descriptor instead.
func (*UpdateParentToCategories) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateParentToCategories) GetSubIds() [][]byte {
	if x != nil {
		return x.SubIds
	}
	return nil
}

func (x *UpdateParentToCategories) GetParentIds() []byte {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

type CheckAvailableSlugParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailableSlugParams) Reset() {
	*x = CheckAvailableSlugParams{}
	mi := &file_catalog_categories_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailableSlugParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailableSlugParams) ProtoMessage() {}

func (x *CheckAvailableSlugParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailableSlugParams.ProtoReflect.Descriptor instead.
func (*CheckAvailableSlugParams) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{7}
}

func (x *CheckAvailableSlugParams) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type SetImageToCategoryParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUuid     []byte                 `protobuf:"bytes,2,opt,name=image_uuid,json=imageUuid,proto3" json:"image_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetImageToCategoryParams) Reset() {
	*x = SetImageToCategoryParams{}
	mi := &file_catalog_categories_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetImageToCategoryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetImageToCategoryParams) ProtoMessage() {}

func (x *SetImageToCategoryParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetImageToCategoryParams.ProtoReflect.Descriptor instead.
func (*SetImageToCategoryParams) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{8}
}

func (x *SetImageToCategoryParams) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetImageToCategoryParams) GetImageUuid() []byte {
	if x != nil {
		return x.ImageUuid
	}
	return nil
}

type OrderSortCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderSort     int32                  `protobuf:"varint,2,opt,name=order_sort,json=orderSort,proto3" json:"order_sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSortCategory) Reset() {
	*x = OrderSortCategory{}
	mi := &file_catalog_categories_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSortCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSortCategory) ProtoMessage() {}

func (x *OrderSortCategory) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSortCategory.ProtoReflect.Descriptor instead.
func (*OrderSortCategory) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{9}
}

func (x *OrderSortCategory) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderSortCategory) GetOrderSort() int32 {
	if x != nil {
		return x.OrderSort
	}
	return 0
}

type UpdateOrderSortToCategoriesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderSortCategory   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderSortToCategoriesParams) Reset() {
	*x = UpdateOrderSortToCategoriesParams{}
	mi := &file_catalog_categories_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderSortToCategoriesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderSortToCategoriesParams) ProtoMessage() {}

func (x *UpdateOrderSortToCategoriesParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderSortToCategoriesParams.ProtoReflect.Descriptor instead.
func (*UpdateOrderSortToCategoriesParams) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrderSortToCategoriesParams) GetList() []*OrderSortCategory {
	if x != nil {
		return x.List
	}
	return nil
}

type GetCategoriesPaginateParams struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Params        *common.GetPaginateParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesPaginateParams) Reset() {
	*x = GetCategoriesPaginateParams{}
	mi := &file_catalog_categories_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesPaginateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesPaginateParams) ProtoMessage() {}

func (x *GetCategoriesPaginateParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesPaginateParams.ProtoReflect.Descriptor instead.
func (*GetCategoriesPaginateParams) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{11}
}

func (x *GetCategoriesPaginateParams) GetParams() *common.GetPaginateParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type GetPaginateCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Category            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Meta          *common.PaginateMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaginateCategoriesResponse) Reset() {
	*x = GetPaginateCategoriesResponse{}
	mi := &file_catalog_categories_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaginateCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaginateCategoriesResponse) ProtoMessage() {}

func (x *GetPaginateCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaginateCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetPaginateCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{12}
}

func (x *GetPaginateCategoriesResponse) GetList() []*Category {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetPaginateCategoriesResponse) GetMeta() *common.PaginateMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetPaginateCategoriesShortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CategoryShort       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Meta          *common.PaginateMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaginateCategoriesShortResponse) Reset() {
	*x = GetPaginateCategoriesShortResponse{}
	mi := &file_catalog_categories_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaginateCategoriesShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaginateCategoriesShortResponse) ProtoMessage() {}

func (x *GetPaginateCategoriesShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaginateCategoriesShortResponse.ProtoReflect.Descriptor instead.
func (*GetPaginateCategoriesShortResponse) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{13}
}

func (x *GetPaginateCategoriesShortResponse) GetList() []*CategoryShort {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetPaginateCategoriesShortResponse) GetMeta() *common.PaginateMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetCategoriesOffsetParams struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Params        *common.GetOffsetParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesOffsetParams) Reset() {
	*x = GetCategoriesOffsetParams{}
	mi := &file_catalog_categories_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesOffsetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesOffsetParams) ProtoMessage() {}

func (x *GetCategoriesOffsetParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesOffsetParams.ProtoReflect.Descriptor instead.
func (*GetCategoriesOffsetParams) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{14}
}

func (x *GetCategoriesOffsetParams) GetParams() *common.GetOffsetParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type GetCategoriesOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Category            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesOffsetResponse) Reset() {
	*x = GetCategoriesOffsetResponse{}
	mi := &file_catalog_categories_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesOffsetResponse) ProtoMessage() {}

func (x *GetCategoriesOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesOffsetResponse) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{15}
}

func (x *GetCategoriesOffsetResponse) GetList() []*Category {
	if x != nil {
		return x.List
	}
	return nil
}

type GetCategoriesShortOffsetParams struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Params        *common.GetOffsetParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesShortOffsetParams) Reset() {
	*x = GetCategoriesShortOffsetParams{}
	mi := &file_catalog_categories_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesShortOffsetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesShortOffsetParams) ProtoMessage() {}

func (x *GetCategoriesShortOffsetParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesShortOffsetParams.ProtoReflect.Descriptor instead.
func (*GetCategoriesShortOffsetParams) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{16}
}

func (x *GetCategoriesShortOffsetParams) GetParams() *common.GetOffsetParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type GetCategoriesShortOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CategoryShort       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesShortOffsetResponse) Reset() {
	*x = GetCategoriesShortOffsetResponse{}
	mi := &file_catalog_categories_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesShortOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesShortOffsetResponse) ProtoMessage() {}

func (x *GetCategoriesShortOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesShortOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesShortOffsetResponse) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{17}
}

func (x *GetCategoriesShortOffsetResponse) GetList() []*CategoryShort {
	if x != nil {
		return x.List
	}
	return nil
}

type GetCategoryByIdParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryByIdParams) Reset() {
	*x = GetCategoryByIdParams{}
	mi := &file_catalog_categories_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryByIdParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryByIdParams) ProtoMessage() {}

func (x *GetCategoryByIdParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryByIdParams.ProtoReflect.Descriptor instead.
func (*GetCategoryByIdParams) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{18}
}

func (x *GetCategoryByIdParams) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCategoriesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryIds   int32                  `protobuf:"varint,1,opt,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoriesParams) Reset() {
	*x = DeleteCategoriesParams{}
	mi := &file_catalog_categories_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoriesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoriesParams) ProtoMessage() {}

func (x *DeleteCategoriesParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoriesParams.ProtoReflect.Descriptor instead.
func (*DeleteCategoriesParams) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteCategoriesParams) GetCategoryIds() int32 {
	if x != nil {
		return x.CategoryIds
	}
	return 0
}

type StatusCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusCategory) Reset() {
	*x = StatusCategory{}
	mi := &file_catalog_categories_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCategory) ProtoMessage() {}

func (x *StatusCategory) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCategory.ProtoReflect.Descriptor instead.
func (*StatusCategory) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{20}
}

func (x *StatusCategory) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatusCategory) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DeleteCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *StatusCategory        `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoriesResponse) Reset() {
	*x = DeleteCategoriesResponse{}
	mi := &file_catalog_categories_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoriesResponse) ProtoMessage() {}

func (x *DeleteCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoriesResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteCategoriesResponse) GetList() *StatusCategory {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateOrderSortToCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *StatusCategory        `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderSortToCategoriesResponse) Reset() {
	*x = UpdateOrderSortToCategoriesResponse{}
	mi := &file_catalog_categories_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderSortToCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderSortToCategoriesResponse) ProtoMessage() {}

func (x *UpdateOrderSortToCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_categories_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderSortToCategoriesResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderSortToCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_categories_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateOrderSortToCategoriesResponse) GetList() *StatusCategory {
	if x != nil {
		return x.List
	}
	return nil
}

var File_catalog_categories_proto protoreflect.FileDescriptor

const file_catalog_categories_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/categories.proto\x12\acatalog\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xd7\x02\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12 \n" +
	"\tparent_id\x18\x02 \x01(\x05H\x00R\bparentId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"order_sort\x18\x06 \x01(\x05R\torderSort\x12\"\n" +
	"\n" +
	"image_uuid\x18\a \x01(\fH\x01R\timageUuid\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\f\n" +
	"\n" +
	"_parent_idB\r\n" +
	"\v_image_uuid\"z\n" +
	"\rCategoryShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\"\n" +
	"\n" +
	"image_uuid\x18\x04 \x01(\fH\x00R\timageUuid\x88\x01\x01B\r\n" +
	"\v_image_uuid\"\xbe\x01\n" +
	"\x14UpsertCategoryParams\x12 \n" +
	"\tparent_id\x18\x01 \x01(\x05H\x00R\bparentId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\"\n" +
	"\n" +
	"image_uuid\x18\x05 \x01(\fH\x01R\timageUuid\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\r\n" +
	"\v_image_uuid\"I\n" +
	"\x14CreateCategoryParams\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.catalog.UpsertCategoryParamsR\x04data\"Y\n" +
	"\x14UpdateCategoryParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x121\n" +
	"\x04data\x18\x02 \x01(\v2\x1d.catalog.UpsertCategoryParamsR\x04data\"I\n" +
	"\x18UpdateActiveToCategories\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\"R\n" +
	"\x18UpdateParentToCategories\x12\x17\n" +
	"\asub_ids\x18\x01 \x03(\fR\x06subIds\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x02 \x01(\fR\tparentIds\".\n" +
	"\x18CheckAvailableSlugParams\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"I\n" +
	"\x18SetImageToCategoryParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"image_uuid\x18\x02 \x01(\fR\timageUuid\"B\n" +
	"\x11OrderSortCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"order_sort\x18\x02 \x01(\x05R\torderSort\"S\n" +
	"!UpdateOrderSortToCategoriesParams\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.catalog.OrderSortCategoryR\x04list\"P\n" +
	"\x1bGetCategoriesPaginateParams\x121\n" +
	"\x06params\x18\x01 \x01(\v2\x19.common.GetPaginateParamsR\x06params\"p\n" +
	"\x1dGetPaginateCategoriesResponse\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.catalog.CategoryR\x04list\x12(\n" +
	"\x04meta\x18\x02 \x01(\v2\x14.common.PaginateMetaR\x04meta\"z\n" +
	"\"GetPaginateCategoriesShortResponse\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.catalog.CategoryShortR\x04list\x12(\n" +
	"\x04meta\x18\x02 \x01(\v2\x14.common.PaginateMetaR\x04meta\"L\n" +
	"\x19GetCategoriesOffsetParams\x12/\n" +
	"\x06params\x18\x01 \x01(\v2\x17.common.GetOffsetParamsR\x06params\"D\n" +
	"\x1bGetCategoriesOffsetResponse\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.catalog.CategoryR\x04list\"Q\n" +
	"\x1eGetCategoriesShortOffsetParams\x12/\n" +
	"\x06params\x18\x01 \x01(\v2\x17.common.GetOffsetParamsR\x06params\"N\n" +
	" GetCategoriesShortOffsetResponse\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.catalog.CategoryShortR\x04list\"'\n" +
	"\x15GetCategoryByIdParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\";\n" +
	"\x16DeleteCategoriesParams\x12!\n" +
	"\fcategory_ids\x18\x01 \x01(\x05R\vcategoryIds\"8\n" +
	"\x0eStatusCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"G\n" +
	"\x18DeleteCategoriesResponse\x12+\n" +
	"\x04list\x18\x01 \x01(\v2\x17.catalog.StatusCategoryR\x04list\"R\n" +
	"#UpdateOrderSortToCategoriesResponse\x12+\n" +
	"\x04list\x18\x01 \x01(\v2\x17.catalog.StatusCategoryR\x04listB8Z6github.com/market-4-test/contract-go/catalog;catalogv1b\x06proto3"

var (
	file_catalog_categories_proto_rawDescOnce sync.Once
	file_catalog_categories_proto_rawDescData []byte
)

func file_catalog_categories_proto_rawDescGZIP() []byte {
	file_catalog_categories_proto_rawDescOnce.Do(func() {
		file_catalog_categories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_categories_proto_rawDesc), len(file_catalog_categories_proto_rawDesc)))
	})
	return file_catalog_categories_proto_rawDescData
}

var file_catalog_categories_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_catalog_categories_proto_goTypes = []any{
	(*Category)(nil),                            // 0: catalog.Category
	(*CategoryShort)(nil),                       // 1: catalog.CategoryShort
	(*UpsertCategoryParams)(nil),                // 2: catalog.UpsertCategoryParams
	(*CreateCategoryParams)(nil),                // 3: catalog.CreateCategoryParams
	(*UpdateCategoryParams)(nil),                // 4: catalog.UpdateCategoryParams
	(*UpdateActiveToCategories)(nil),            // 5: catalog.UpdateActiveToCategories
	(*UpdateParentToCategories)(nil),            // 6: catalog.UpdateParentToCategories
	(*CheckAvailableSlugParams)(nil),            // 7: catalog.CheckAvailableSlugParams
	(*SetImageToCategoryParams)(nil),            // 8: catalog.SetImageToCategoryParams
	(*OrderSortCategory)(nil),                   // 9: catalog.OrderSortCategory
	(*UpdateOrderSortToCategoriesParams)(nil),   // 10: catalog.UpdateOrderSortToCategoriesParams
	(*GetCategoriesPaginateParams)(nil),         // 11: catalog.GetCategoriesPaginateParams
	(*GetPaginateCategoriesResponse)(nil),       // 12: catalog.GetPaginateCategoriesResponse
	(*GetPaginateCategoriesShortResponse)(nil),  // 13: catalog.GetPaginateCategoriesShortResponse
	(*GetCategoriesOffsetParams)(nil),           // 14: catalog.GetCategoriesOffsetParams
	(*GetCategoriesOffsetResponse)(nil),         // 15: catalog.GetCategoriesOffsetResponse
	(*GetCategoriesShortOffsetParams)(nil),      // 16: catalog.GetCategoriesShortOffsetParams
	(*GetCategoriesShortOffsetResponse)(nil),    // 17: catalog.GetCategoriesShortOffsetResponse
	(*GetCategoryByIdParams)(nil),               // 18: catalog.GetCategoryByIdParams
	(*DeleteCategoriesParams)(nil),              // 19: catalog.DeleteCategoriesParams
	(*StatusCategory)(nil),                      // 20: catalog.StatusCategory
	(*DeleteCategoriesResponse)(nil),            // 21: catalog.DeleteCategoriesResponse
	(*UpdateOrderSortToCategoriesResponse)(nil), // 22: catalog.UpdateOrderSortToCategoriesResponse
	(*timestamppb.Timestamp)(nil),               // 23: google.protobuf.Timestamp
	(*common.GetPaginateParams)(nil),            // 24: common.GetPaginateParams
	(*common.PaginateMeta)(nil),                 // 25: common.PaginateMeta
	(*common.GetOffsetParams)(nil),              // 26: common.GetOffsetParams
}
var file_catalog_categories_proto_depIdxs = []int32{
	23, // 0: catalog.Category.created_at:type_name -> google.protobuf.Timestamp
	23, // 1: catalog.Category.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: catalog.CreateCategoryParams.data:type_name -> catalog.UpsertCategoryParams
	2,  // 3: catalog.UpdateCategoryParams.data:type_name -> catalog.UpsertCategoryParams
	9,  // 4: catalog.UpdateOrderSortToCategoriesParams.list:type_name -> catalog.OrderSortCategory
	24, // 5: catalog.GetCategoriesPaginateParams.params:type_name -> common.GetPaginateParams
	0,  // 6: catalog.GetPaginateCategoriesResponse.list:type_name -> catalog.Category
	25, // 7: catalog.GetPaginateCategoriesResponse.meta:type_name -> common.PaginateMeta
	1,  // 8: catalog.GetPaginateCategoriesShortResponse.list:type_name -> catalog.CategoryShort
	25, // 9: catalog.GetPaginateCategoriesShortResponse.meta:type_name -> common.PaginateMeta
	26, // 10: catalog.GetCategoriesOffsetParams.params:type_name -> common.GetOffsetParams
	0,  // 11: catalog.GetCategoriesOffsetResponse.list:type_name -> catalog.Category
	26, // 12: catalog.GetCategoriesShortOffsetParams.params:type_name -> common.GetOffsetParams
	1,  // 13: catalog.GetCategoriesShortOffsetResponse.list:type_name -> catalog.CategoryShort
	20, // 14: catalog.DeleteCategoriesResponse.list:type_name -> catalog.StatusCategory
	20, // 15: catalog.UpdateOrderSortToCategoriesResponse.list:type_name -> catalog.StatusCategory
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_catalog_categories_proto_init() }
func file_catalog_categories_proto_init() {
	if File_catalog_categories_proto != nil {
		return
	}
	file_catalog_categories_proto_msgTypes[0].OneofWrappers = []any{}
	file_catalog_categories_proto_msgTypes[1].OneofWrappers = []any{}
	file_catalog_categories_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_categories_proto_rawDesc), len(file_catalog_categories_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_categories_proto_goTypes,
		DependencyIndexes: file_catalog_categories_proto_depIdxs,
		MessageInfos:      file_catalog_categories_proto_msgTypes,
	}.Build()
	File_catalog_categories_proto = out.File
	file_catalog_categories_proto_goTypes = nil
	file_catalog_categories_proto_depIdxs = nil
}
