// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: catalog/products.proto

package catalogv1

import (
	common "github.com/market-4-test/contract-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductStatus int32

const (
	ProductStatus_UNSPECIFIED ProductStatus = 0
	ProductStatus_DRAFT       ProductStatus = 1
	ProductStatus_PUBLISHED   ProductStatus = 2
	ProductStatus_ARCHIVED    ProductStatus = 3 // deleted
)

// Enum value maps for ProductStatus.
var (
	ProductStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "DRAFT",
		2: "PUBLISHED",
		3: "ARCHIVED",
	}
	ProductStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"DRAFT":       1,
		"PUBLISHED":   2,
		"ARCHIVED":    3,
	}
)

func (x ProductStatus) Enum() *ProductStatus {
	p := new(ProductStatus)
	*p = x
	return p
}

func (x ProductStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_products_proto_enumTypes[0].Descriptor()
}

func (ProductStatus) Type() protoreflect.EnumType {
	return &file_catalog_products_proto_enumTypes[0]
}

func (x ProductStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductStatus.Descriptor instead.
func (ProductStatus) EnumDescriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{0}
}

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int32                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // -1 || > 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_catalog_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{0}
}

func (x *Stock) GetWarehouseId() int32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *Stock) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ProductImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SortOrder     int32                  `protobuf:"varint,2,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductImage) Reset() {
	*x = ProductImage{}
	mi := &file_catalog_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductImage) ProtoMessage() {}

func (x *ProductImage) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductImage.ProtoReflect.Descriptor instead.
func (*ProductImage) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{1}
}

func (x *ProductImage) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *ProductImage) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ProductMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         uint32                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	BrandId       *int32                 `protobuf:"varint,6,opt,name=brand_id,json=brandId,proto3,oneof" json:"brand_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductMeta) Reset() {
	*x = ProductMeta{}
	mi := &file_catalog_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductMeta) ProtoMessage() {}

func (x *ProductMeta) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductMeta.ProtoReflect.Descriptor instead.
func (*ProductMeta) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{2}
}

func (x *ProductMeta) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *ProductMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductMeta) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductMeta) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductMeta) GetBrandId() int32 {
	if x != nil && x.BrandId != nil {
		return *x.BrandId
	}
	return 0
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ProductMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Images        []*ProductImage        `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Stocks        []*Stock               `protobuf:"bytes,3,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{3}
}

func (x *Product) GetMeta() *ProductMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Product) GetImages() []*ProductImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type ProductShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ProductMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Image         []byte                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductShort) Reset() {
	*x = ProductShort{}
	mi := &file_catalog_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductShort) ProtoMessage() {}

func (x *ProductShort) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductShort.ProtoReflect.Descriptor instead.
func (*ProductShort) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{4}
}

func (x *ProductShort) GetMeta() *ProductMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ProductShort) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type GetProductsMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ProductStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=catalog.ProductStatus,oneof" json:"status,omitempty"`
	Query         *string                `protobuf:"bytes,2,opt,name=query,proto3,oneof" json:"query,omitempty"`
	CategoryIds   []int32                `protobuf:"varint,3,rep,packed,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	BrandIds      []int32                `protobuf:"varint,4,rep,packed,name=brand_ids,json=brandIds,proto3" json:"brand_ids,omitempty"`
	TagIds        []int32                `protobuf:"varint,5,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsMeta) Reset() {
	*x = GetProductsMeta{}
	mi := &file_catalog_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsMeta) ProtoMessage() {}

func (x *GetProductsMeta) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsMeta.ProtoReflect.Descriptor instead.
func (*GetProductsMeta) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductsMeta) GetStatus() ProductStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ProductStatus_UNSPECIFIED
}

func (x *GetProductsMeta) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *GetProductsMeta) GetCategoryIds() []int32 {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *GetProductsMeta) GetBrandIds() []int32 {
	if x != nil {
		return x.BrandIds
	}
	return nil
}

func (x *GetProductsMeta) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type GetProductsPaginateParams struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Params        *common.GetPaginateParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Meta          *GetProductsMeta          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsPaginateParams) Reset() {
	*x = GetProductsPaginateParams{}
	mi := &file_catalog_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsPaginateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsPaginateParams) ProtoMessage() {}

func (x *GetProductsPaginateParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsPaginateParams.ProtoReflect.Descriptor instead.
func (*GetProductsPaginateParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductsPaginateParams) GetParams() *common.GetPaginateParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GetProductsPaginateParams) GetMeta() *GetProductsMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetProductsShortPaginateParams struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Params        *common.GetPaginateParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Meta          *GetProductsMeta          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsShortPaginateParams) Reset() {
	*x = GetProductsShortPaginateParams{}
	mi := &file_catalog_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsShortPaginateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsShortPaginateParams) ProtoMessage() {}

func (x *GetProductsShortPaginateParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsShortPaginateParams.ProtoReflect.Descriptor instead.
func (*GetProductsShortPaginateParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductsShortPaginateParams) GetParams() *common.GetPaginateParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GetProductsShortPaginateParams) GetMeta() *GetProductsMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetProductsOffsetParams struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Params        *common.GetOffsetParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Status        *ProductStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=catalog.ProductStatus,oneof" json:"status,omitempty"`
	Meta          *GetProductsMeta        `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsOffsetParams) Reset() {
	*x = GetProductsOffsetParams{}
	mi := &file_catalog_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsOffsetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsOffsetParams) ProtoMessage() {}

func (x *GetProductsOffsetParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsOffsetParams.ProtoReflect.Descriptor instead.
func (*GetProductsOffsetParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductsOffsetParams) GetParams() *common.GetOffsetParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GetProductsOffsetParams) GetStatus() ProductStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ProductStatus_UNSPECIFIED
}

func (x *GetProductsOffsetParams) GetMeta() *GetProductsMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetProductsShortOffsetParams struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Params        *common.GetOffsetParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Meta          *GetProductsMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsShortOffsetParams) Reset() {
	*x = GetProductsShortOffsetParams{}
	mi := &file_catalog_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsShortOffsetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsShortOffsetParams) ProtoMessage() {}

func (x *GetProductsShortOffsetParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsShortOffsetParams.ProtoReflect.Descriptor instead.
func (*GetProductsShortOffsetParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{9}
}

func (x *GetProductsShortOffsetParams) GetParams() *common.GetOffsetParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GetProductsShortOffsetParams) GetMeta() *GetProductsMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetProductsPaginateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *Product               `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	Meta          *common.PaginateMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsPaginateResponse) Reset() {
	*x = GetProductsPaginateResponse{}
	mi := &file_catalog_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsPaginateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsPaginateResponse) ProtoMessage() {}

func (x *GetProductsPaginateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsPaginateResponse.ProtoReflect.Descriptor instead.
func (*GetProductsPaginateResponse) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{10}
}

func (x *GetProductsPaginateResponse) GetList() *Product {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetProductsPaginateResponse) GetMeta() *common.PaginateMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetProductsShortPaginateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *ProductShort          `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	Meta          *common.PaginateMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsShortPaginateResponse) Reset() {
	*x = GetProductsShortPaginateResponse{}
	mi := &file_catalog_products_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsShortPaginateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsShortPaginateResponse) ProtoMessage() {}

func (x *GetProductsShortPaginateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsShortPaginateResponse.ProtoReflect.Descriptor instead.
func (*GetProductsShortPaginateResponse) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{11}
}

func (x *GetProductsShortPaginateResponse) GetList() *ProductShort {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetProductsShortPaginateResponse) GetMeta() *common.PaginateMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetProductsOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *Product               `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsOffsetResponse) Reset() {
	*x = GetProductsOffsetResponse{}
	mi := &file_catalog_products_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsOffsetResponse) ProtoMessage() {}

func (x *GetProductsOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetProductsOffsetResponse) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{12}
}

func (x *GetProductsOffsetResponse) GetList() *Product {
	if x != nil {
		return x.List
	}
	return nil
}

type GetProductsShortOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *ProductShort          `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsShortOffsetResponse) Reset() {
	*x = GetProductsShortOffsetResponse{}
	mi := &file_catalog_products_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsShortOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsShortOffsetResponse) ProtoMessage() {}

func (x *GetProductsShortOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsShortOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetProductsShortOffsetResponse) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{13}
}

func (x *GetProductsShortOffsetResponse) GetList() *ProductShort {
	if x != nil {
		return x.List
	}
	return nil
}

type GetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *Product               `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_catalog_products_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{14}
}

func (x *GetProductsResponse) GetList() *Product {
	if x != nil {
		return x.List
	}
	return nil
}

type GetProductsShortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *ProductShort          `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsShortResponse) Reset() {
	*x = GetProductsShortResponse{}
	mi := &file_catalog_products_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsShortResponse) ProtoMessage() {}

func (x *GetProductsShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsShortResponse.ProtoReflect.Descriptor instead.
func (*GetProductsShortResponse) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{15}
}

func (x *GetProductsShortResponse) GetList() *ProductShort {
	if x != nil {
		return x.List
	}
	return nil
}

type GetProductsByUuidsParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          [][]byte               `protobuf:"bytes,1,rep,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByUuidsParams) Reset() {
	*x = GetProductsByUuidsParams{}
	mi := &file_catalog_products_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByUuidsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByUuidsParams) ProtoMessage() {}

func (x *GetProductsByUuidsParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByUuidsParams.ProtoReflect.Descriptor instead.
func (*GetProductsByUuidsParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{16}
}

func (x *GetProductsByUuidsParams) GetUuid() [][]byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type GetProductByUuidParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByUuidParams) Reset() {
	*x = GetProductByUuidParams{}
	mi := &file_catalog_products_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByUuidParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByUuidParams) ProtoMessage() {}

func (x *GetProductByUuidParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByUuidParams.ProtoReflect.Descriptor instead.
func (*GetProductByUuidParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{17}
}

func (x *GetProductByUuidParams) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type UpsertProductMetaParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         uint32                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	BrandId       *int32                 `protobuf:"varint,5,opt,name=brand_id,json=brandId,proto3,oneof" json:"brand_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProductMetaParams) Reset() {
	*x = UpsertProductMetaParams{}
	mi := &file_catalog_products_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProductMetaParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProductMetaParams) ProtoMessage() {}

func (x *UpsertProductMetaParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProductMetaParams.ProtoReflect.Descriptor instead.
func (*UpsertProductMetaParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{18}
}

func (x *UpsertProductMetaParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertProductMetaParams) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpsertProductMetaParams) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpsertProductMetaParams) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpsertProductMetaParams) GetBrandId() int32 {
	if x != nil && x.BrandId != nil {
		return *x.BrandId
	}
	return 0
}

type CreateProductParams struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Data          *UpsertProductMetaParams `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductParams) Reset() {
	*x = CreateProductParams{}
	mi := &file_catalog_products_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductParams) ProtoMessage() {}

func (x *CreateProductParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductParams.ProtoReflect.Descriptor instead.
func (*CreateProductParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{19}
}

func (x *CreateProductParams) GetData() *UpsertProductMetaParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateProductMetaParams struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Uuid          []byte                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Data          *UpsertProductMetaParams `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductMetaParams) Reset() {
	*x = UpdateProductMetaParams{}
	mi := &file_catalog_products_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductMetaParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductMetaParams) ProtoMessage() {}

func (x *UpdateProductMetaParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductMetaParams.ProtoReflect.Descriptor instead.
func (*UpdateProductMetaParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateProductMetaParams) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateProductMetaParams) GetData() *UpsertProductMetaParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateProductsStatusParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ProductStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=catalog.ProductStatus" json:"status,omitempty"`
	Uuids         [][]byte               `protobuf:"bytes,2,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsStatusParams) Reset() {
	*x = UpdateProductsStatusParams{}
	mi := &file_catalog_products_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsStatusParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsStatusParams) ProtoMessage() {}

func (x *UpdateProductsStatusParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsStatusParams.ProtoReflect.Descriptor instead.
func (*UpdateProductsStatusParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateProductsStatusParams) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_UNSPECIFIED
}

func (x *UpdateProductsStatusParams) GetUuids() [][]byte {
	if x != nil {
		return x.Uuids
	}
	return nil
}

type UpdateProductsStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuids         []byte                 `protobuf:"bytes,1,opt,name=uuids,proto3" json:"uuids,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsStatus) Reset() {
	*x = UpdateProductsStatus{}
	mi := &file_catalog_products_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsStatus) ProtoMessage() {}

func (x *UpdateProductsStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsStatus.ProtoReflect.Descriptor instead.
func (*UpdateProductsStatus) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateProductsStatus) GetUuids() []byte {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *UpdateProductsStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpdateProductsStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      *UpdateProductsStatus  `protobuf:"bytes,1,opt,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsStatusResponse) Reset() {
	*x = UpdateProductsStatusResponse{}
	mi := &file_catalog_products_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsStatusResponse) ProtoMessage() {}

func (x *UpdateProductsStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductsStatusResponse) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateProductsStatusResponse) GetStatuses() *UpdateProductsStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type UpdateProductPriceParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         uint32                 `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Uuids         [][]byte               `protobuf:"bytes,2,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductPriceParams) Reset() {
	*x = UpdateProductPriceParams{}
	mi := &file_catalog_products_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductPriceParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductPriceParams) ProtoMessage() {}

func (x *UpdateProductPriceParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductPriceParams.ProtoReflect.Descriptor instead.
func (*UpdateProductPriceParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateProductPriceParams) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductPriceParams) GetUuids() [][]byte {
	if x != nil {
		return x.Uuids
	}
	return nil
}

type UpdateProductsStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int32                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // -1 - delete || >= 0 update
	ProductUuid   []byte                 `protobuf:"bytes,3,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsStock) Reset() {
	*x = UpdateProductsStock{}
	mi := &file_catalog_products_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsStock) ProtoMessage() {}

func (x *UpdateProductsStock) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsStock.ProtoReflect.Descriptor instead.
func (*UpdateProductsStock) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateProductsStock) GetWarehouseId() int32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *UpdateProductsStock) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UpdateProductsStock) GetProductUuid() []byte {
	if x != nil {
		return x.ProductUuid
	}
	return nil
}

type UpdateProductsStocksParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        []*UpdateProductsStock `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsStocksParams) Reset() {
	*x = UpdateProductsStocksParams{}
	mi := &file_catalog_products_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsStocksParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsStocksParams) ProtoMessage() {}

func (x *UpdateProductsStocksParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsStocksParams.ProtoReflect.Descriptor instead.
func (*UpdateProductsStocksParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateProductsStocksParams) GetStocks() []*UpdateProductsStock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type UpdateProductsStockStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   int32                  `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	ProductUuid   []byte                 `protobuf:"bytes,2,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsStockStatus) Reset() {
	*x = UpdateProductsStockStatus{}
	mi := &file_catalog_products_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsStockStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsStockStatus) ProtoMessage() {}

func (x *UpdateProductsStockStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsStockStatus.ProtoReflect.Descriptor instead.
func (*UpdateProductsStockStatus) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateProductsStockStatus) GetWarehouseId() int32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *UpdateProductsStockStatus) GetProductUuid() []byte {
	if x != nil {
		return x.ProductUuid
	}
	return nil
}

func (x *UpdateProductsStockStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpdateProductsStocksResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Statuses      []*UpdateProductsStockStatus `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsStocksResponse) Reset() {
	*x = UpdateProductsStocksResponse{}
	mi := &file_catalog_products_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsStocksResponse) ProtoMessage() {}

func (x *UpdateProductsStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsStocksResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductsStocksResponse) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateProductsStocksResponse) GetStatuses() []*UpdateProductsStockStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type UpdateProductsPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductUuid   []byte                 `protobuf:"bytes,1,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	Price         int32                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsPrice) Reset() {
	*x = UpdateProductsPrice{}
	mi := &file_catalog_products_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsPrice) ProtoMessage() {}

func (x *UpdateProductsPrice) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsPrice.ProtoReflect.Descriptor instead.
func (*UpdateProductsPrice) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateProductsPrice) GetProductUuid() []byte {
	if x != nil {
		return x.ProductUuid
	}
	return nil
}

func (x *UpdateProductsPrice) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateProductsPricesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prices        []*UpdateProductsPrice `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsPricesParams) Reset() {
	*x = UpdateProductsPricesParams{}
	mi := &file_catalog_products_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsPricesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsPricesParams) ProtoMessage() {}

func (x *UpdateProductsPricesParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsPricesParams.ProtoReflect.Descriptor instead.
func (*UpdateProductsPricesParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateProductsPricesParams) GetPrices() []*UpdateProductsPrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

type UpdateProductsPriceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductUuid   []byte                 `protobuf:"bytes,2,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsPriceStatus) Reset() {
	*x = UpdateProductsPriceStatus{}
	mi := &file_catalog_products_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsPriceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsPriceStatus) ProtoMessage() {}

func (x *UpdateProductsPriceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsPriceStatus.ProtoReflect.Descriptor instead.
func (*UpdateProductsPriceStatus) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateProductsPriceStatus) GetProductUuid() []byte {
	if x != nil {
		return x.ProductUuid
	}
	return nil
}

func (x *UpdateProductsPriceStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpdateProductsPricesResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Statuses      []*UpdateProductsPriceStatus `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsPricesResponse) Reset() {
	*x = UpdateProductsPricesResponse{}
	mi := &file_catalog_products_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsPricesResponse) ProtoMessage() {}

func (x *UpdateProductsPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsPricesResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductsPricesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateProductsPricesResponse) GetStatuses() []*UpdateProductsPriceStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type CheckProductAvailableSlugParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductAvailableSlugParams) Reset() {
	*x = CheckProductAvailableSlugParams{}
	mi := &file_catalog_products_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductAvailableSlugParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductAvailableSlugParams) ProtoMessage() {}

func (x *CheckProductAvailableSlugParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductAvailableSlugParams.ProtoReflect.Descriptor instead.
func (*CheckProductAvailableSlugParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{33}
}

func (x *CheckProductAvailableSlugParams) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ToggleAttachProductsToCategories struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductUuids  [][]byte               `protobuf:"bytes,1,rep,name=product_uuids,json=productUuids,proto3" json:"product_uuids,omitempty"`
	CategoryIds   int32                  `protobuf:"varint,2,opt,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleAttachProductsToCategories) Reset() {
	*x = ToggleAttachProductsToCategories{}
	mi := &file_catalog_products_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleAttachProductsToCategories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleAttachProductsToCategories) ProtoMessage() {}

func (x *ToggleAttachProductsToCategories) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleAttachProductsToCategories.ProtoReflect.Descriptor instead.
func (*ToggleAttachProductsToCategories) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{34}
}

func (x *ToggleAttachProductsToCategories) GetProductUuids() [][]byte {
	if x != nil {
		return x.ProductUuids
	}
	return nil
}

func (x *ToggleAttachProductsToCategories) GetCategoryIds() int32 {
	if x != nil {
		return x.CategoryIds
	}
	return 0
}

type ToggleAttachProductsToCategoryParams struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	List          []*ToggleAttachProductsToCategories `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleAttachProductsToCategoryParams) Reset() {
	*x = ToggleAttachProductsToCategoryParams{}
	mi := &file_catalog_products_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleAttachProductsToCategoryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleAttachProductsToCategoryParams) ProtoMessage() {}

func (x *ToggleAttachProductsToCategoryParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleAttachProductsToCategoryParams.ProtoReflect.Descriptor instead.
func (*ToggleAttachProductsToCategoryParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{35}
}

func (x *ToggleAttachProductsToCategoryParams) GetList() []*ToggleAttachProductsToCategories {
	if x != nil {
		return x.List
	}
	return nil
}

type CommonToggleAttachProductStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductUuid   []byte                 `protobuf:"bytes,1,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonToggleAttachProductStatus) Reset() {
	*x = CommonToggleAttachProductStatus{}
	mi := &file_catalog_products_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonToggleAttachProductStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonToggleAttachProductStatus) ProtoMessage() {}

func (x *CommonToggleAttachProductStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonToggleAttachProductStatus.ProtoReflect.Descriptor instead.
func (*CommonToggleAttachProductStatus) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{36}
}

func (x *CommonToggleAttachProductStatus) GetProductUuid() []byte {
	if x != nil {
		return x.ProductUuid
	}
	return nil
}

func (x *CommonToggleAttachProductStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type CommonToggleAttachProductsResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Statuses      *CommonToggleAttachProductStatus `protobuf:"bytes,1,opt,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonToggleAttachProductsResponse) Reset() {
	*x = CommonToggleAttachProductsResponse{}
	mi := &file_catalog_products_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonToggleAttachProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonToggleAttachProductsResponse) ProtoMessage() {}

func (x *CommonToggleAttachProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonToggleAttachProductsResponse.ProtoReflect.Descriptor instead.
func (*CommonToggleAttachProductsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{37}
}

func (x *CommonToggleAttachProductsResponse) GetStatuses() *CommonToggleAttachProductStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ToggleAttachProductsToBrands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductUuids  [][]byte               `protobuf:"bytes,1,rep,name=product_uuids,json=productUuids,proto3" json:"product_uuids,omitempty"`
	BrandIds      int32                  `protobuf:"varint,2,opt,name=brand_ids,json=brandIds,proto3" json:"brand_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleAttachProductsToBrands) Reset() {
	*x = ToggleAttachProductsToBrands{}
	mi := &file_catalog_products_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleAttachProductsToBrands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleAttachProductsToBrands) ProtoMessage() {}

func (x *ToggleAttachProductsToBrands) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleAttachProductsToBrands.ProtoReflect.Descriptor instead.
func (*ToggleAttachProductsToBrands) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{38}
}

func (x *ToggleAttachProductsToBrands) GetProductUuids() [][]byte {
	if x != nil {
		return x.ProductUuids
	}
	return nil
}

func (x *ToggleAttachProductsToBrands) GetBrandIds() int32 {
	if x != nil {
		return x.BrandIds
	}
	return 0
}

type ToggleAttachProductsToBrandsParams struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	List          []*ToggleAttachProductsToBrands `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleAttachProductsToBrandsParams) Reset() {
	*x = ToggleAttachProductsToBrandsParams{}
	mi := &file_catalog_products_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleAttachProductsToBrandsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleAttachProductsToBrandsParams) ProtoMessage() {}

func (x *ToggleAttachProductsToBrandsParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleAttachProductsToBrandsParams.ProtoReflect.Descriptor instead.
func (*ToggleAttachProductsToBrandsParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{39}
}

func (x *ToggleAttachProductsToBrandsParams) GetList() []*ToggleAttachProductsToBrands {
	if x != nil {
		return x.List
	}
	return nil
}

type ToggleAttachProductsToTags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductUuids  [][]byte               `protobuf:"bytes,1,rep,name=product_uuids,json=productUuids,proto3" json:"product_uuids,omitempty"`
	TagIds        int32                  `protobuf:"varint,2,opt,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleAttachProductsToTags) Reset() {
	*x = ToggleAttachProductsToTags{}
	mi := &file_catalog_products_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleAttachProductsToTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleAttachProductsToTags) ProtoMessage() {}

func (x *ToggleAttachProductsToTags) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleAttachProductsToTags.ProtoReflect.Descriptor instead.
func (*ToggleAttachProductsToTags) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{40}
}

func (x *ToggleAttachProductsToTags) GetProductUuids() [][]byte {
	if x != nil {
		return x.ProductUuids
	}
	return nil
}

func (x *ToggleAttachProductsToTags) GetTagIds() int32 {
	if x != nil {
		return x.TagIds
	}
	return 0
}

type ToggleAttachProductsToTagsParams struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	List          []*ToggleAttachProductsToBrands `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleAttachProductsToTagsParams) Reset() {
	*x = ToggleAttachProductsToTagsParams{}
	mi := &file_catalog_products_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleAttachProductsToTagsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleAttachProductsToTagsParams) ProtoMessage() {}

func (x *ToggleAttachProductsToTagsParams) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_products_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleAttachProductsToTagsParams.ProtoReflect.Descriptor instead.
func (*ToggleAttachProductsToTagsParams) Descriptor() ([]byte, []int) {
	return file_catalog_products_proto_rawDescGZIP(), []int{41}
}

func (x *ToggleAttachProductsToTagsParams) GetList() []*ToggleAttachProductsToBrands {
	if x != nil {
		return x.List
	}
	return nil
}

var File_catalog_products_proto protoreflect.FileDescriptor

const file_catalog_products_proto_rawDesc = "" +
	"\n" +
	"\x16catalog/products.proto\x12\acatalog\x1a\x13common/common.proto\"@\n" +
	"\x05Stock\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x05R\vwarehouseId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"A\n" +
	"\fProductImage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x02 \x01(\x05R\tsortOrder\"\xae\x01\n" +
	"\vProductMeta\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\rR\x05price\x12\x1e\n" +
	"\bbrand_id\x18\x06 \x01(\x05H\x00R\abrandId\x88\x01\x01B\v\n" +
	"\t_brand_id\"\x8a\x01\n" +
	"\aProduct\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.catalog.ProductMetaR\x04meta\x12-\n" +
	"\x06images\x18\x02 \x03(\v2\x15.catalog.ProductImageR\x06images\x12&\n" +
	"\x06stocks\x18\x03 \x03(\v2\x0e.catalog.StockR\x06stocks\"N\n" +
	"\fProductShort\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.catalog.ProductMetaR\x04meta\x12\x14\n" +
	"\x05image\x18\x02 \x01(\fR\x05image\"\xcf\x01\n" +
	"\x0fGetProductsMeta\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.catalog.ProductStatusH\x00R\x06status\x88\x01\x01\x12\x19\n" +
	"\x05query\x18\x02 \x01(\tH\x01R\x05query\x88\x01\x01\x12!\n" +
	"\fcategory_ids\x18\x03 \x03(\x05R\vcategoryIds\x12\x1b\n" +
	"\tbrand_ids\x18\x04 \x03(\x05R\bbrandIds\x12\x17\n" +
	"\atag_ids\x18\x05 \x03(\x05R\x06tagIdsB\t\n" +
	"\a_statusB\b\n" +
	"\x06_query\"|\n" +
	"\x19GetProductsPaginateParams\x121\n" +
	"\x06params\x18\x01 \x01(\v2\x19.common.GetPaginateParamsR\x06params\x12,\n" +
	"\x04meta\x18\x02 \x01(\v2\x18.catalog.GetProductsMetaR\x04meta\"\x81\x01\n" +
	"\x1eGetProductsShortPaginateParams\x121\n" +
	"\x06params\x18\x01 \x01(\v2\x19.common.GetPaginateParamsR\x06params\x12,\n" +
	"\x04meta\x18\x02 \x01(\v2\x18.catalog.GetProductsMetaR\x04meta\"\xb8\x01\n" +
	"\x17GetProductsOffsetParams\x12/\n" +
	"\x06params\x18\x01 \x01(\v2\x17.common.GetOffsetParamsR\x06params\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.catalog.ProductStatusH\x00R\x06status\x88\x01\x01\x12,\n" +
	"\x04meta\x18\x03 \x01(\v2\x18.catalog.GetProductsMetaR\x04metaB\t\n" +
	"\a_status\"}\n" +
	"\x1cGetProductsShortOffsetParams\x12/\n" +
	"\x06params\x18\x01 \x01(\v2\x17.common.GetOffsetParamsR\x06params\x12,\n" +
	"\x04meta\x18\x02 \x01(\v2\x18.catalog.GetProductsMetaR\x04meta\"m\n" +
	"\x1bGetProductsPaginateResponse\x12$\n" +
	"\x04list\x18\x01 \x01(\v2\x10.catalog.ProductR\x04list\x12(\n" +
	"\x04meta\x18\x02 \x01(\v2\x14.common.PaginateMetaR\x04meta\"w\n" +
	" GetProductsShortPaginateResponse\x12)\n" +
	"\x04list\x18\x01 \x01(\v2\x15.catalog.ProductShortR\x04list\x12(\n" +
	"\x04meta\x18\x02 \x01(\v2\x14.common.PaginateMetaR\x04meta\"A\n" +
	"\x19GetProductsOffsetResponse\x12$\n" +
	"\x04list\x18\x01 \x01(\v2\x10.catalog.ProductR\x04list\"K\n" +
	"\x1eGetProductsShortOffsetResponse\x12)\n" +
	"\x04list\x18\x01 \x01(\v2\x15.catalog.ProductShortR\x04list\";\n" +
	"\x13GetProductsResponse\x12$\n" +
	"\x04list\x18\x01 \x01(\v2\x10.catalog.ProductR\x04list\"E\n" +
	"\x18GetProductsShortResponse\x12)\n" +
	"\x04list\x18\x01 \x01(\v2\x15.catalog.ProductShortR\x04list\".\n" +
	"\x18GetProductsByUuidsParams\x12\x12\n" +
	"\x04uuid\x18\x01 \x03(\fR\x04uuid\",\n" +
	"\x16GetProductByUuidParams\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"\xa6\x01\n" +
	"\x17UpsertProductMetaParams\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\rR\x05price\x12\x1e\n" +
	"\bbrand_id\x18\x05 \x01(\x05H\x00R\abrandId\x88\x01\x01B\v\n" +
	"\t_brand_id\"K\n" +
	"\x13CreateProductParams\x124\n" +
	"\x04data\x18\x01 \x01(\v2 .catalog.UpsertProductMetaParamsR\x04data\"c\n" +
	"\x17UpdateProductMetaParams\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x124\n" +
	"\x04data\x18\x02 \x01(\v2 .catalog.UpsertProductMetaParamsR\x04data\"b\n" +
	"\x1aUpdateProductsStatusParams\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.catalog.ProductStatusR\x06status\x12\x14\n" +
	"\x05uuids\x18\x02 \x03(\fR\x05uuids\"D\n" +
	"\x14UpdateProductsStatus\x12\x14\n" +
	"\x05uuids\x18\x01 \x01(\fR\x05uuids\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"Y\n" +
	"\x1cUpdateProductsStatusResponse\x129\n" +
	"\bstatuses\x18\x01 \x01(\v2\x1d.catalog.UpdateProductsStatusR\bstatuses\"F\n" +
	"\x18UpdateProductPriceParams\x12\x14\n" +
	"\x05price\x18\x01 \x01(\rR\x05price\x12\x14\n" +
	"\x05uuids\x18\x02 \x03(\fR\x05uuids\"q\n" +
	"\x13UpdateProductsStock\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x05R\vwarehouseId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12!\n" +
	"\fproduct_uuid\x18\x03 \x01(\fR\vproductUuid\"R\n" +
	"\x1aUpdateProductsStocksParams\x124\n" +
	"\x06stocks\x18\x01 \x03(\v2\x1c.catalog.UpdateProductsStockR\x06stocks\"y\n" +
	"\x19UpdateProductsStockStatus\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\x05R\vwarehouseId\x12!\n" +
	"\fproduct_uuid\x18\x02 \x01(\fR\vproductUuid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\"^\n" +
	"\x1cUpdateProductsStocksResponse\x12>\n" +
	"\bstatuses\x18\x01 \x03(\v2\".catalog.UpdateProductsStockStatusR\bstatuses\"N\n" +
	"\x13UpdateProductsPrice\x12!\n" +
	"\fproduct_uuid\x18\x01 \x01(\fR\vproductUuid\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x05R\x05price\"R\n" +
	"\x1aUpdateProductsPricesParams\x124\n" +
	"\x06prices\x18\x01 \x03(\v2\x1c.catalog.UpdateProductsPriceR\x06prices\"V\n" +
	"\x19UpdateProductsPriceStatus\x12!\n" +
	"\fproduct_uuid\x18\x02 \x01(\fR\vproductUuid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\"^\n" +
	"\x1cUpdateProductsPricesResponse\x12>\n" +
	"\bstatuses\x18\x01 \x03(\v2\".catalog.UpdateProductsPriceStatusR\bstatuses\"5\n" +
	"\x1fCheckProductAvailableSlugParams\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"j\n" +
	" ToggleAttachProductsToCategories\x12#\n" +
	"\rproduct_uuids\x18\x01 \x03(\fR\fproductUuids\x12!\n" +
	"\fcategory_ids\x18\x02 \x01(\x05R\vcategoryIds\"e\n" +
	"$ToggleAttachProductsToCategoryParams\x12=\n" +
	"\x04list\x18\x01 \x03(\v2).catalog.ToggleAttachProductsToCategoriesR\x04list\"\\\n" +
	"\x1fCommonToggleAttachProductStatus\x12!\n" +
	"\fproduct_uuid\x18\x01 \x01(\fR\vproductUuid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"j\n" +
	"\"CommonToggleAttachProductsResponse\x12D\n" +
	"\bstatuses\x18\x01 \x01(\v2(.catalog.CommonToggleAttachProductStatusR\bstatuses\"`\n" +
	"\x1cToggleAttachProductsToBrands\x12#\n" +
	"\rproduct_uuids\x18\x01 \x03(\fR\fproductUuids\x12\x1b\n" +
	"\tbrand_ids\x18\x02 \x01(\x05R\bbrandIds\"_\n" +
	"\"ToggleAttachProductsToBrandsParams\x129\n" +
	"\x04list\x18\x01 \x03(\v2%.catalog.ToggleAttachProductsToBrandsR\x04list\"Z\n" +
	"\x1aToggleAttachProductsToTags\x12#\n" +
	"\rproduct_uuids\x18\x01 \x03(\fR\fproductUuids\x12\x17\n" +
	"\atag_ids\x18\x02 \x01(\x05R\x06tagIds\"]\n" +
	" ToggleAttachProductsToTagsParams\x129\n" +
	"\x04list\x18\x01 \x03(\v2%.catalog.ToggleAttachProductsToBrandsR\x04list*H\n" +
	"\rProductStatus\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DRAFT\x10\x01\x12\r\n" +
	"\tPUBLISHED\x10\x02\x12\f\n" +
	"\bARCHIVED\x10\x03B8Z6github.com/market-4-test/contract-go/catalog;catalogv1b\x06proto3"

var (
	file_catalog_products_proto_rawDescOnce sync.Once
	file_catalog_products_proto_rawDescData []byte
)

func file_catalog_products_proto_rawDescGZIP() []byte {
	file_catalog_products_proto_rawDescOnce.Do(func() {
		file_catalog_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_products_proto_rawDesc), len(file_catalog_products_proto_rawDesc)))
	})
	return file_catalog_products_proto_rawDescData
}

var file_catalog_products_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_catalog_products_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_catalog_products_proto_goTypes = []any{
	(ProductStatus)(0),                           // 0: catalog.ProductStatus
	(*Stock)(nil),                                // 1: catalog.Stock
	(*ProductImage)(nil),                         // 2: catalog.ProductImage
	(*ProductMeta)(nil),                          // 3: catalog.ProductMeta
	(*Product)(nil),                              // 4: catalog.Product
	(*ProductShort)(nil),                         // 5: catalog.ProductShort
	(*GetProductsMeta)(nil),                      // 6: catalog.GetProductsMeta
	(*GetProductsPaginateParams)(nil),            // 7: catalog.GetProductsPaginateParams
	(*GetProductsShortPaginateParams)(nil),       // 8: catalog.GetProductsShortPaginateParams
	(*GetProductsOffsetParams)(nil),              // 9: catalog.GetProductsOffsetParams
	(*GetProductsShortOffsetParams)(nil),         // 10: catalog.GetProductsShortOffsetParams
	(*GetProductsPaginateResponse)(nil),          // 11: catalog.GetProductsPaginateResponse
	(*GetProductsShortPaginateResponse)(nil),     // 12: catalog.GetProductsShortPaginateResponse
	(*GetProductsOffsetResponse)(nil),            // 13: catalog.GetProductsOffsetResponse
	(*GetProductsShortOffsetResponse)(nil),       // 14: catalog.GetProductsShortOffsetResponse
	(*GetProductsResponse)(nil),                  // 15: catalog.GetProductsResponse
	(*GetProductsShortResponse)(nil),             // 16: catalog.GetProductsShortResponse
	(*GetProductsByUuidsParams)(nil),             // 17: catalog.GetProductsByUuidsParams
	(*GetProductByUuidParams)(nil),               // 18: catalog.GetProductByUuidParams
	(*UpsertProductMetaParams)(nil),              // 19: catalog.UpsertProductMetaParams
	(*CreateProductParams)(nil),                  // 20: catalog.CreateProductParams
	(*UpdateProductMetaParams)(nil),              // 21: catalog.UpdateProductMetaParams
	(*UpdateProductsStatusParams)(nil),           // 22: catalog.UpdateProductsStatusParams
	(*UpdateProductsStatus)(nil),                 // 23: catalog.UpdateProductsStatus
	(*UpdateProductsStatusResponse)(nil),         // 24: catalog.UpdateProductsStatusResponse
	(*UpdateProductPriceParams)(nil),             // 25: catalog.UpdateProductPriceParams
	(*UpdateProductsStock)(nil),                  // 26: catalog.UpdateProductsStock
	(*UpdateProductsStocksParams)(nil),           // 27: catalog.UpdateProductsStocksParams
	(*UpdateProductsStockStatus)(nil),            // 28: catalog.UpdateProductsStockStatus
	(*UpdateProductsStocksResponse)(nil),         // 29: catalog.UpdateProductsStocksResponse
	(*UpdateProductsPrice)(nil),                  // 30: catalog.UpdateProductsPrice
	(*UpdateProductsPricesParams)(nil),           // 31: catalog.UpdateProductsPricesParams
	(*UpdateProductsPriceStatus)(nil),            // 32: catalog.UpdateProductsPriceStatus
	(*UpdateProductsPricesResponse)(nil),         // 33: catalog.UpdateProductsPricesResponse
	(*CheckProductAvailableSlugParams)(nil),      // 34: catalog.CheckProductAvailableSlugParams
	(*ToggleAttachProductsToCategories)(nil),     // 35: catalog.ToggleAttachProductsToCategories
	(*ToggleAttachProductsToCategoryParams)(nil), // 36: catalog.ToggleAttachProductsToCategoryParams
	(*CommonToggleAttachProductStatus)(nil),      // 37: catalog.CommonToggleAttachProductStatus
	(*CommonToggleAttachProductsResponse)(nil),   // 38: catalog.CommonToggleAttachProductsResponse
	(*ToggleAttachProductsToBrands)(nil),         // 39: catalog.ToggleAttachProductsToBrands
	(*ToggleAttachProductsToBrandsParams)(nil),   // 40: catalog.ToggleAttachProductsToBrandsParams
	(*ToggleAttachProductsToTags)(nil),           // 41: catalog.ToggleAttachProductsToTags
	(*ToggleAttachProductsToTagsParams)(nil),     // 42: catalog.ToggleAttachProductsToTagsParams
	(*common.GetPaginateParams)(nil),             // 43: common.GetPaginateParams
	(*common.GetOffsetParams)(nil),               // 44: common.GetOffsetParams
	(*common.PaginateMeta)(nil),                  // 45: common.PaginateMeta
}
var file_catalog_products_proto_depIdxs = []int32{
	3,  // 0: catalog.Product.meta:type_name -> catalog.ProductMeta
	2,  // 1: catalog.Product.images:type_name -> catalog.ProductImage
	1,  // 2: catalog.Product.stocks:type_name -> catalog.Stock
	3,  // 3: catalog.ProductShort.meta:type_name -> catalog.ProductMeta
	0,  // 4: catalog.GetProductsMeta.status:type_name -> catalog.ProductStatus
	43, // 5: catalog.GetProductsPaginateParams.params:type_name -> common.GetPaginateParams
	6,  // 6: catalog.GetProductsPaginateParams.meta:type_name -> catalog.GetProductsMeta
	43, // 7: catalog.GetProductsShortPaginateParams.params:type_name -> common.GetPaginateParams
	6,  // 8: catalog.GetProductsShortPaginateParams.meta:type_name -> catalog.GetProductsMeta
	44, // 9: catalog.GetProductsOffsetParams.params:type_name -> common.GetOffsetParams
	0,  // 10: catalog.GetProductsOffsetParams.status:type_name -> catalog.ProductStatus
	6,  // 11: catalog.GetProductsOffsetParams.meta:type_name -> catalog.GetProductsMeta
	44, // 12: catalog.GetProductsShortOffsetParams.params:type_name -> common.GetOffsetParams
	6,  // 13: catalog.GetProductsShortOffsetParams.meta:type_name -> catalog.GetProductsMeta
	4,  // 14: catalog.GetProductsPaginateResponse.list:type_name -> catalog.Product
	45, // 15: catalog.GetProductsPaginateResponse.meta:type_name -> common.PaginateMeta
	5,  // 16: catalog.GetProductsShortPaginateResponse.list:type_name -> catalog.ProductShort
	45, // 17: catalog.GetProductsShortPaginateResponse.meta:type_name -> common.PaginateMeta
	4,  // 18: catalog.GetProductsOffsetResponse.list:type_name -> catalog.Product
	5,  // 19: catalog.GetProductsShortOffsetResponse.list:type_name -> catalog.ProductShort
	4,  // 20: catalog.GetProductsResponse.list:type_name -> catalog.Product
	5,  // 21: catalog.GetProductsShortResponse.list:type_name -> catalog.ProductShort
	19, // 22: catalog.CreateProductParams.data:type_name -> catalog.UpsertProductMetaParams
	19, // 23: catalog.UpdateProductMetaParams.data:type_name -> catalog.UpsertProductMetaParams
	0,  // 24: catalog.UpdateProductsStatusParams.status:type_name -> catalog.ProductStatus
	23, // 25: catalog.UpdateProductsStatusResponse.statuses:type_name -> catalog.UpdateProductsStatus
	26, // 26: catalog.UpdateProductsStocksParams.stocks:type_name -> catalog.UpdateProductsStock
	28, // 27: catalog.UpdateProductsStocksResponse.statuses:type_name -> catalog.UpdateProductsStockStatus
	30, // 28: catalog.UpdateProductsPricesParams.prices:type_name -> catalog.UpdateProductsPrice
	32, // 29: catalog.UpdateProductsPricesResponse.statuses:type_name -> catalog.UpdateProductsPriceStatus
	35, // 30: catalog.ToggleAttachProductsToCategoryParams.list:type_name -> catalog.ToggleAttachProductsToCategories
	37, // 31: catalog.CommonToggleAttachProductsResponse.statuses:type_name -> catalog.CommonToggleAttachProductStatus
	39, // 32: catalog.ToggleAttachProductsToBrandsParams.list:type_name -> catalog.ToggleAttachProductsToBrands
	39, // 33: catalog.ToggleAttachProductsToTagsParams.list:type_name -> catalog.ToggleAttachProductsToBrands
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_catalog_products_proto_init() }
func file_catalog_products_proto_init() {
	if File_catalog_products_proto != nil {
		return
	}
	file_catalog_products_proto_msgTypes[2].OneofWrappers = []any{}
	file_catalog_products_proto_msgTypes[5].OneofWrappers = []any{}
	file_catalog_products_proto_msgTypes[8].OneofWrappers = []any{}
	file_catalog_products_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_products_proto_rawDesc), len(file_catalog_products_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_products_proto_goTypes,
		DependencyIndexes: file_catalog_products_proto_depIdxs,
		EnumInfos:         file_catalog_products_proto_enumTypes,
		MessageInfos:      file_catalog_products_proto_msgTypes,
	}.Build()
	File_catalog_products_proto = out.File
	file_catalog_products_proto_goTypes = nil
	file_catalog_products_proto_depIdxs = nil
}
