// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: space/permissions.proto

package spacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_space_permissions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_space_permissions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_space_permissions_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPermissionsParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        *int32                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3,oneof" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsParams) Reset() {
	*x = GetPermissionsParams{}
	mi := &file_space_permissions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsParams) ProtoMessage() {}

func (x *GetPermissionsParams) ProtoReflect() protoreflect.Message {
	mi := &file_space_permissions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsParams.ProtoReflect.Descriptor instead.
func (*GetPermissionsParams) Descriptor() ([]byte, []int) {
	return file_space_permissions_proto_rawDescGZIP(), []int{1}
}

func (x *GetPermissionsParams) GetRoleId() int32 {
	if x != nil && x.RoleId != nil {
		return *x.RoleId
	}
	return 0
}

type GetPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *Permission            `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsResponse) Reset() {
	*x = GetPermissionsResponse{}
	mi := &file_space_permissions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsResponse) ProtoMessage() {}

func (x *GetPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_space_permissions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_space_permissions_proto_rawDescGZIP(), []int{2}
}

func (x *GetPermissionsResponse) GetList() *Permission {
	if x != nil {
		return x.List
	}
	return nil
}

type CreatePermissionParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionParams) Reset() {
	*x = CreatePermissionParams{}
	mi := &file_space_permissions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionParams) ProtoMessage() {}

func (x *CreatePermissionParams) ProtoReflect() protoreflect.Message {
	mi := &file_space_permissions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionParams.ProtoReflect.Descriptor instead.
func (*CreatePermissionParams) Descriptor() ([]byte, []int) {
	return file_space_permissions_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePermissionParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdatePermissionParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionParams) Reset() {
	*x = UpdatePermissionParams{}
	mi := &file_space_permissions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionParams) ProtoMessage() {}

func (x *UpdatePermissionParams) ProtoReflect() protoreflect.Message {
	mi := &file_space_permissions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionParams.ProtoReflect.Descriptor instead.
func (*UpdatePermissionParams) Descriptor() ([]byte, []int) {
	return file_space_permissions_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePermissionParams) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePermissionParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_space_permissions_proto protoreflect.FileDescriptor

const file_space_permissions_proto_rawDesc = "" +
	"\n" +
	"\x17space/permissions.proto\x12\x05space\"0\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\x14GetPermissionsParams\x12\x1c\n" +
	"\arole_id\x18\x01 \x01(\x05H\x00R\x06roleId\x88\x01\x01B\n" +
	"\n" +
	"\b_role_id\"?\n" +
	"\x16GetPermissionsResponse\x12%\n" +
	"\x04list\x18\x01 \x01(\v2\x11.space.PermissionR\x04list\",\n" +
	"\x16CreatePermissionParams\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\x16UpdatePermissionParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB4Z2github.com/market-4-test/contract-go/space;spacev1b\x06proto3"

var (
	file_space_permissions_proto_rawDescOnce sync.Once
	file_space_permissions_proto_rawDescData []byte
)

func file_space_permissions_proto_rawDescGZIP() []byte {
	file_space_permissions_proto_rawDescOnce.Do(func() {
		file_space_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_space_permissions_proto_rawDesc), len(file_space_permissions_proto_rawDesc)))
	})
	return file_space_permissions_proto_rawDescData
}

var file_space_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_space_permissions_proto_goTypes = []any{
	(*Permission)(nil),             // 0: space.Permission
	(*GetPermissionsParams)(nil),   // 1: space.GetPermissionsParams
	(*GetPermissionsResponse)(nil), // 2: space.GetPermissionsResponse
	(*CreatePermissionParams)(nil), // 3: space.CreatePermissionParams
	(*UpdatePermissionParams)(nil), // 4: space.UpdatePermissionParams
}
var file_space_permissions_proto_depIdxs = []int32{
	0, // 0: space.GetPermissionsResponse.list:type_name -> space.Permission
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_space_permissions_proto_init() }
func file_space_permissions_proto_init() {
	if File_space_permissions_proto != nil {
		return
	}
	file_space_permissions_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_space_permissions_proto_rawDesc), len(file_space_permissions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_space_permissions_proto_goTypes,
		DependencyIndexes: file_space_permissions_proto_depIdxs,
		MessageInfos:      file_space_permissions_proto_msgTypes,
	}.Build()
	File_space_permissions_proto = out.File
	file_space_permissions_proto_goTypes = nil
	file_space_permissions_proto_depIdxs = nil
}
