// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: space/roles.proto

package spacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CanDelete     bool                   `protobuf:"varint,3,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_space_roles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_space_roles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_space_roles_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

type GetRolesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolesParams) Reset() {
	*x = GetRolesParams{}
	mi := &file_space_roles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolesParams) ProtoMessage() {}

func (x *GetRolesParams) ProtoReflect() protoreflect.Message {
	mi := &file_space_roles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolesParams.ProtoReflect.Descriptor instead.
func (*GetRolesParams) Descriptor() ([]byte, []int) {
	return file_space_roles_proto_rawDescGZIP(), []int{1}
}

type GetRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *Role                  `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolesResponse) Reset() {
	*x = GetRolesResponse{}
	mi := &file_space_roles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolesResponse) ProtoMessage() {}

func (x *GetRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_space_roles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolesResponse.ProtoReflect.Descriptor instead.
func (*GetRolesResponse) Descriptor() ([]byte, []int) {
	return file_space_roles_proto_rawDescGZIP(), []int{2}
}

func (x *GetRolesResponse) GetList() *Role {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateRoleParams struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AttachPermissionIds int32                  `protobuf:"varint,2,opt,name=attach_permission_ids,json=attachPermissionIds,proto3" json:"attach_permission_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateRoleParams) Reset() {
	*x = CreateRoleParams{}
	mi := &file_space_roles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleParams) ProtoMessage() {}

func (x *CreateRoleParams) ProtoReflect() protoreflect.Message {
	mi := &file_space_roles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleParams.ProtoReflect.Descriptor instead.
func (*CreateRoleParams) Descriptor() ([]byte, []int) {
	return file_space_roles_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleParams) GetAttachPermissionIds() int32 {
	if x != nil {
		return x.AttachPermissionIds
	}
	return 0
}

type UpdateRoleParams struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AttachPermissionIds int32                  `protobuf:"varint,3,opt,name=attach_permission_ids,json=attachPermissionIds,proto3" json:"attach_permission_ids,omitempty"`
	DetachPermissionIds int32                  `protobuf:"varint,4,opt,name=detach_permission_ids,json=detachPermissionIds,proto3" json:"detach_permission_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateRoleParams) Reset() {
	*x = UpdateRoleParams{}
	mi := &file_space_roles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleParams) ProtoMessage() {}

func (x *UpdateRoleParams) ProtoReflect() protoreflect.Message {
	mi := &file_space_roles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleParams.ProtoReflect.Descriptor instead.
func (*UpdateRoleParams) Descriptor() ([]byte, []int) {
	return file_space_roles_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoleParams) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleParams) GetAttachPermissionIds() int32 {
	if x != nil {
		return x.AttachPermissionIds
	}
	return 0
}

func (x *UpdateRoleParams) GetDetachPermissionIds() int32 {
	if x != nil {
		return x.DetachPermissionIds
	}
	return 0
}

type DeleteRoleParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleParams) Reset() {
	*x = DeleteRoleParams{}
	mi := &file_space_roles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleParams) ProtoMessage() {}

func (x *DeleteRoleParams) ProtoReflect() protoreflect.Message {
	mi := &file_space_roles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleParams.ProtoReflect.Descriptor instead.
func (*DeleteRoleParams) Descriptor() ([]byte, []int) {
	return file_space_roles_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRoleParams) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRoleResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AttachedEmployees []int32                `protobuf:"varint,1,rep,packed,name=attached_employees,json=attachedEmployees,proto3" json:"attached_employees,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_space_roles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_space_roles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_space_roles_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRoleResponse) GetAttachedEmployees() []int32 {
	if x != nil {
		return x.AttachedEmployees
	}
	return nil
}

type ToggleRoleToEmployeesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int32                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	EmployeeId    []int32                `protobuf:"varint,2,rep,packed,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleRoleToEmployeesParams) Reset() {
	*x = ToggleRoleToEmployeesParams{}
	mi := &file_space_roles_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleRoleToEmployeesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleRoleToEmployeesParams) ProtoMessage() {}

func (x *ToggleRoleToEmployeesParams) ProtoReflect() protoreflect.Message {
	mi := &file_space_roles_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleRoleToEmployeesParams.ProtoReflect.Descriptor instead.
func (*ToggleRoleToEmployeesParams) Descriptor() ([]byte, []int) {
	return file_space_roles_proto_rawDescGZIP(), []int{7}
}

func (x *ToggleRoleToEmployeesParams) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ToggleRoleToEmployeesParams) GetEmployeeId() []int32 {
	if x != nil {
		return x.EmployeeId
	}
	return nil
}

var File_space_roles_proto protoreflect.FileDescriptor

const file_space_roles_proto_rawDesc = "" +
	"\n" +
	"\x11space/roles.proto\x12\x05space\"I\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x03 \x01(\bR\tcanDelete\"\x10\n" +
	"\x0eGetRolesParams\"3\n" +
	"\x10GetRolesResponse\x12\x1f\n" +
	"\x04list\x18\x01 \x01(\v2\v.space.RoleR\x04list\"Z\n" +
	"\x10CreateRoleParams\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x15attach_permission_ids\x18\x02 \x01(\x05R\x13attachPermissionIds\"\x9e\x01\n" +
	"\x10UpdateRoleParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x15attach_permission_ids\x18\x03 \x01(\x05R\x13attachPermissionIds\x122\n" +
	"\x15detach_permission_ids\x18\x04 \x01(\x05R\x13detachPermissionIds\"\"\n" +
	"\x10DeleteRoleParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"C\n" +
	"\x12DeleteRoleResponse\x12-\n" +
	"\x12attached_employees\x18\x01 \x03(\x05R\x11attachedEmployees\"W\n" +
	"\x1bToggleRoleToEmployeesParams\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x05R\x06roleId\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x03(\x05R\n" +
	"employeeIdB4Z2github.com/market-4-test/contract-go/space;spacev1b\x06proto3"

var (
	file_space_roles_proto_rawDescOnce sync.Once
	file_space_roles_proto_rawDescData []byte
)

func file_space_roles_proto_rawDescGZIP() []byte {
	file_space_roles_proto_rawDescOnce.Do(func() {
		file_space_roles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_space_roles_proto_rawDesc), len(file_space_roles_proto_rawDesc)))
	})
	return file_space_roles_proto_rawDescData
}

var file_space_roles_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_space_roles_proto_goTypes = []any{
	(*Role)(nil),                        // 0: space.Role
	(*GetRolesParams)(nil),              // 1: space.GetRolesParams
	(*GetRolesResponse)(nil),            // 2: space.GetRolesResponse
	(*CreateRoleParams)(nil),            // 3: space.CreateRoleParams
	(*UpdateRoleParams)(nil),            // 4: space.UpdateRoleParams
	(*DeleteRoleParams)(nil),            // 5: space.DeleteRoleParams
	(*DeleteRoleResponse)(nil),          // 6: space.DeleteRoleResponse
	(*ToggleRoleToEmployeesParams)(nil), // 7: space.ToggleRoleToEmployeesParams
}
var file_space_roles_proto_depIdxs = []int32{
	0, // 0: space.GetRolesResponse.list:type_name -> space.Role
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_space_roles_proto_init() }
func file_space_roles_proto_init() {
	if File_space_roles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_space_roles_proto_rawDesc), len(file_space_roles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_space_roles_proto_goTypes,
		DependencyIndexes: file_space_roles_proto_depIdxs,
		MessageInfos:      file_space_roles_proto_msgTypes,
	}.Build()
	File_space_roles_proto = out.File
	file_space_roles_proto_goTypes = nil
	file_space_roles_proto_depIdxs = nil
}
