// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: space/space.proto

package spacev1

import (
	common "github.com/market-4-test/contract-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_space_space_proto protoreflect.FileDescriptor

const file_space_space_proto_rawDesc = "" +
	"\n" +
	"\x11space/space.proto\x12\x05space\x1a\x13common/common.proto\x1a\x10space/auth.proto\x1a\x14space/profiles.proto\x1a\x11space/roles.proto\x1a\x17space/permissions.proto\x1a\x15space/employees.proto2\x8e\n" +
	"\n" +
	"\x05Space\x129\n" +
	"\fAuthenticate\x12\x19.space.AuthenticateParams\x1a\x0e.common.Status\x120\n" +
	"\x05Login\x12\x12.space.LoginParams\x1a\x13.space.AuthResponse\x12>\n" +
	"\fRefreshToken\x12\x19.space.RefreshTokenParams\x1a\x13.space.AuthResponse\x12=\n" +
	"\x0eChangePassword\x12\x1b.space.ChangePasswordParams\x1a\x0e.common.Status\x125\n" +
	"\n" +
	"GetProfile\x12\x17.space.GetProfileParams\x1a\x0e.space.Profile\x12:\n" +
	"\bGetRoles\x12\x15.space.GetRolesParams\x1a\x17.space.GetRolesResponse\x12?\n" +
	"\n" +
	"CreateRole\x12\x17.space.CreateRoleParams\x1a\x18.common.ValidationErrors\x12?\n" +
	"\n" +
	"UpdateRole\x12\x17.space.CreateRoleParams\x1a\x18.common.ValidationErrors\x12@\n" +
	"\n" +
	"DeleteRole\x12\x17.space.DeleteRoleParams\x1a\x19.space.DeleteRoleResponse\x12J\n" +
	"\x14AttachRoleToEmployee\x12\".space.ToggleRoleToEmployeesParams\x1a\x0e.common.Status\x12L\n" +
	"\x16DetachRoleFromEmployee\x12\".space.ToggleRoleToEmployeesParams\x1a\x0e.common.Status\x12L\n" +
	"\x0eGetPermissions\x12\x1b.space.GetPermissionsParams\x1a\x1d.space.GetPermissionsResponse\x12A\n" +
	"\x10CreatePermission\x12\x1d.space.CreatePermissionParams\x1a\x0e.common.Status\x12A\n" +
	"\x10UpdatePermission\x12\x1d.space.UpdatePermissionParams\x1a\x0e.common.Status\x12F\n" +
	"\fGetEmployees\x12\x19.space.GetEmployeesParams\x1a\x1b.space.GetEmployeesResponse\x12G\n" +
	"\x0eCreateEmployee\x12\x1b.space.CreateEmployeeParams\x1a\x18.common.ValidationErrors\x12G\n" +
	"\x0eUpdateEmployee\x12\x1b.space.UpdateEmployeeParams\x1a\x18.common.ValidationErrors\x12]\n" +
	"\x1eCheckEmployeeAvailableUsername\x12+.space.CheckEmployeeAvailableUsernameParams\x1a\x0e.common.Status\x12;\n" +
	"\rBlockEmployee\x12\x1a.space.BlockEmployeeParams\x1a\x0e.common.StatusB4Z2github.com/market-4-test/contract-go/space;spacev1b\x06proto3"

var file_space_space_proto_goTypes = []any{
	(*AuthenticateParams)(nil),                   // 0: space.AuthenticateParams
	(*LoginParams)(nil),                          // 1: space.LoginParams
	(*RefreshTokenParams)(nil),                   // 2: space.RefreshTokenParams
	(*ChangePasswordParams)(nil),                 // 3: space.ChangePasswordParams
	(*GetProfileParams)(nil),                     // 4: space.GetProfileParams
	(*GetRolesParams)(nil),                       // 5: space.GetRolesParams
	(*CreateRoleParams)(nil),                     // 6: space.CreateRoleParams
	(*DeleteRoleParams)(nil),                     // 7: space.DeleteRoleParams
	(*ToggleRoleToEmployeesParams)(nil),          // 8: space.ToggleRoleToEmployeesParams
	(*GetPermissionsParams)(nil),                 // 9: space.GetPermissionsParams
	(*CreatePermissionParams)(nil),               // 10: space.CreatePermissionParams
	(*UpdatePermissionParams)(nil),               // 11: space.UpdatePermissionParams
	(*GetEmployeesParams)(nil),                   // 12: space.GetEmployeesParams
	(*CreateEmployeeParams)(nil),                 // 13: space.CreateEmployeeParams
	(*UpdateEmployeeParams)(nil),                 // 14: space.UpdateEmployeeParams
	(*CheckEmployeeAvailableUsernameParams)(nil), // 15: space.CheckEmployeeAvailableUsernameParams
	(*BlockEmployeeParams)(nil),                  // 16: space.BlockEmployeeParams
	(*common.Status)(nil),                        // 17: common.Status
	(*AuthResponse)(nil),                         // 18: space.AuthResponse
	(*Profile)(nil),                              // 19: space.Profile
	(*GetRolesResponse)(nil),                     // 20: space.GetRolesResponse
	(*common.ValidationErrors)(nil),              // 21: common.ValidationErrors
	(*DeleteRoleResponse)(nil),                   // 22: space.DeleteRoleResponse
	(*GetPermissionsResponse)(nil),               // 23: space.GetPermissionsResponse
	(*GetEmployeesResponse)(nil),                 // 24: space.GetEmployeesResponse
}
var file_space_space_proto_depIdxs = []int32{
	0,  // 0: space.Space.Authenticate:input_type -> space.AuthenticateParams
	1,  // 1: space.Space.Login:input_type -> space.LoginParams
	2,  // 2: space.Space.RefreshToken:input_type -> space.RefreshTokenParams
	3,  // 3: space.Space.ChangePassword:input_type -> space.ChangePasswordParams
	4,  // 4: space.Space.GetProfile:input_type -> space.GetProfileParams
	5,  // 5: space.Space.GetRoles:input_type -> space.GetRolesParams
	6,  // 6: space.Space.CreateRole:input_type -> space.CreateRoleParams
	6,  // 7: space.Space.UpdateRole:input_type -> space.CreateRoleParams
	7,  // 8: space.Space.DeleteRole:input_type -> space.DeleteRoleParams
	8,  // 9: space.Space.AttachRoleToEmployee:input_type -> space.ToggleRoleToEmployeesParams
	8,  // 10: space.Space.DetachRoleFromEmployee:input_type -> space.ToggleRoleToEmployeesParams
	9,  // 11: space.Space.GetPermissions:input_type -> space.GetPermissionsParams
	10, // 12: space.Space.CreatePermission:input_type -> space.CreatePermissionParams
	11, // 13: space.Space.UpdatePermission:input_type -> space.UpdatePermissionParams
	12, // 14: space.Space.GetEmployees:input_type -> space.GetEmployeesParams
	13, // 15: space.Space.CreateEmployee:input_type -> space.CreateEmployeeParams
	14, // 16: space.Space.UpdateEmployee:input_type -> space.UpdateEmployeeParams
	15, // 17: space.Space.CheckEmployeeAvailableUsername:input_type -> space.CheckEmployeeAvailableUsernameParams
	16, // 18: space.Space.BlockEmployee:input_type -> space.BlockEmployeeParams
	17, // 19: space.Space.Authenticate:output_type -> common.Status
	18, // 20: space.Space.Login:output_type -> space.AuthResponse
	18, // 21: space.Space.RefreshToken:output_type -> space.AuthResponse
	17, // 22: space.Space.ChangePassword:output_type -> common.Status
	19, // 23: space.Space.GetProfile:output_type -> space.Profile
	20, // 24: space.Space.GetRoles:output_type -> space.GetRolesResponse
	21, // 25: space.Space.CreateRole:output_type -> common.ValidationErrors
	21, // 26: space.Space.UpdateRole:output_type -> common.ValidationErrors
	22, // 27: space.Space.DeleteRole:output_type -> space.DeleteRoleResponse
	17, // 28: space.Space.AttachRoleToEmployee:output_type -> common.Status
	17, // 29: space.Space.DetachRoleFromEmployee:output_type -> common.Status
	23, // 30: space.Space.GetPermissions:output_type -> space.GetPermissionsResponse
	17, // 31: space.Space.CreatePermission:output_type -> common.Status
	17, // 32: space.Space.UpdatePermission:output_type -> common.Status
	24, // 33: space.Space.GetEmployees:output_type -> space.GetEmployeesResponse
	21, // 34: space.Space.CreateEmployee:output_type -> common.ValidationErrors
	21, // 35: space.Space.UpdateEmployee:output_type -> common.ValidationErrors
	17, // 36: space.Space.CheckEmployeeAvailableUsername:output_type -> common.Status
	17, // 37: space.Space.BlockEmployee:output_type -> common.Status
	19, // [19:38] is the sub-list for method output_type
	0,  // [0:19] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_space_space_proto_init() }
func file_space_space_proto_init() {
	if File_space_space_proto != nil {
		return
	}
	file_space_auth_proto_init()
	file_space_profiles_proto_init()
	file_space_roles_proto_init()
	file_space_permissions_proto_init()
	file_space_employees_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_space_space_proto_rawDesc), len(file_space_space_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_space_space_proto_goTypes,
		DependencyIndexes: file_space_space_proto_depIdxs,
	}.Build()
	File_space_space_proto = out.File
	file_space_space_proto_goTypes = nil
	file_space_space_proto_depIdxs = nil
}
