// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: assistant/assistant.proto

package assistantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Assistant_GetSuggestedTagsByText_FullMethodName = "/assistant.Assistant/GetSuggestedTagsByText"
	Assistant_GenerateContentByText_FullMethodName  = "/assistant.Assistant/GenerateContentByText"
)

// AssistantClient is the client API for Assistant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssistantClient interface {
	GetSuggestedTagsByText(ctx context.Context, in *GetSuggestedTagsByTextParams, opts ...grpc.CallOption) (*GetSuggestedTagsByTextResponse, error)
	GenerateContentByText(ctx context.Context, in *GenerateContentByTextParams, opts ...grpc.CallOption) (*GenerateContentByTextResponse, error)
}

type assistantClient struct {
	cc grpc.ClientConnInterface
}

func NewAssistantClient(cc grpc.ClientConnInterface) AssistantClient {
	return &assistantClient{cc}
}

func (c *assistantClient) GetSuggestedTagsByText(ctx context.Context, in *GetSuggestedTagsByTextParams, opts ...grpc.CallOption) (*GetSuggestedTagsByTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSuggestedTagsByTextResponse)
	err := c.cc.Invoke(ctx, Assistant_GetSuggestedTagsByText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantClient) GenerateContentByText(ctx context.Context, in *GenerateContentByTextParams, opts ...grpc.CallOption) (*GenerateContentByTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateContentByTextResponse)
	err := c.cc.Invoke(ctx, Assistant_GenerateContentByText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssistantServer is the server API for Assistant service.
// All implementations must embed UnimplementedAssistantServer
// for forward compatibility.
type AssistantServer interface {
	GetSuggestedTagsByText(context.Context, *GetSuggestedTagsByTextParams) (*GetSuggestedTagsByTextResponse, error)
	GenerateContentByText(context.Context, *GenerateContentByTextParams) (*GenerateContentByTextResponse, error)
	mustEmbedUnimplementedAssistantServer()
}

// UnimplementedAssistantServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssistantServer struct{}

func (UnimplementedAssistantServer) GetSuggestedTagsByText(context.Context, *GetSuggestedTagsByTextParams) (*GetSuggestedTagsByTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuggestedTagsByText not implemented")
}
func (UnimplementedAssistantServer) GenerateContentByText(context.Context, *GenerateContentByTextParams) (*GenerateContentByTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateContentByText not implemented")
}
func (UnimplementedAssistantServer) mustEmbedUnimplementedAssistantServer() {}
func (UnimplementedAssistantServer) testEmbeddedByValue()                   {}

// UnsafeAssistantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssistantServer will
// result in compilation errors.
type UnsafeAssistantServer interface {
	mustEmbedUnimplementedAssistantServer()
}

func RegisterAssistantServer(s grpc.ServiceRegistrar, srv AssistantServer) {
	// If the following call pancis, it indicates UnimplementedAssistantServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Assistant_ServiceDesc, srv)
}

func _Assistant_GetSuggestedTagsByText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuggestedTagsByTextParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServer).GetSuggestedTagsByText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Assistant_GetSuggestedTagsByText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServer).GetSuggestedTagsByText(ctx, req.(*GetSuggestedTagsByTextParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Assistant_GenerateContentByText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateContentByTextParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServer).GenerateContentByText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Assistant_GenerateContentByText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServer).GenerateContentByText(ctx, req.(*GenerateContentByTextParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Assistant_ServiceDesc is the grpc.ServiceDesc for Assistant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Assistant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assistant.Assistant",
	HandlerType: (*AssistantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuggestedTagsByText",
			Handler:    _Assistant_GetSuggestedTagsByText_Handler,
		},
		{
			MethodName: "GenerateContentByText",
			Handler:    _Assistant_GenerateContentByText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assistant/assistant.proto",
}
