// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: logistic/logistic.proto

package logisticv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Warehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_logistic_logistic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_logistic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_logistic_logistic_proto_rawDescGZIP(), []int{0}
}

func (x *Warehouse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Warehouse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Warehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Warehouse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type WarehouseShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseShort) Reset() {
	*x = WarehouseShort{}
	mi := &file_logistic_logistic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseShort) ProtoMessage() {}

func (x *WarehouseShort) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_logistic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseShort.ProtoReflect.Descriptor instead.
func (*WarehouseShort) Descriptor() ([]byte, []int) {
	return file_logistic_logistic_proto_rawDescGZIP(), []int{1}
}

func (x *WarehouseShort) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WarehouseShort) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WarehouseShort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetWarehousesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehousesParams) Reset() {
	*x = GetWarehousesParams{}
	mi := &file_logistic_logistic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehousesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehousesParams) ProtoMessage() {}

func (x *GetWarehousesParams) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_logistic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehousesParams.ProtoReflect.Descriptor instead.
func (*GetWarehousesParams) Descriptor() ([]byte, []int) {
	return file_logistic_logistic_proto_rawDescGZIP(), []int{2}
}

func (x *GetWarehousesParams) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetWarehousesShortParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehousesShortParams) Reset() {
	*x = GetWarehousesShortParams{}
	mi := &file_logistic_logistic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehousesShortParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehousesShortParams) ProtoMessage() {}

func (x *GetWarehousesShortParams) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_logistic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehousesShortParams.ProtoReflect.Descriptor instead.
func (*GetWarehousesShortParams) Descriptor() ([]byte, []int) {
	return file_logistic_logistic_proto_rawDescGZIP(), []int{3}
}

func (x *GetWarehousesShortParams) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetWarehousesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouses    []*Warehouse           `protobuf:"bytes,1,rep,name=warehouses,proto3" json:"warehouses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehousesResponse) Reset() {
	*x = GetWarehousesResponse{}
	mi := &file_logistic_logistic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehousesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehousesResponse) ProtoMessage() {}

func (x *GetWarehousesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_logistic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehousesResponse.ProtoReflect.Descriptor instead.
func (*GetWarehousesResponse) Descriptor() ([]byte, []int) {
	return file_logistic_logistic_proto_rawDescGZIP(), []int{4}
}

func (x *GetWarehousesResponse) GetWarehouses() []*Warehouse {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

type GetWarehousesShortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouses    []*WarehouseShort      `protobuf:"bytes,1,rep,name=warehouses,proto3" json:"warehouses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehousesShortResponse) Reset() {
	*x = GetWarehousesShortResponse{}
	mi := &file_logistic_logistic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehousesShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehousesShortResponse) ProtoMessage() {}

func (x *GetWarehousesShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_logistic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehousesShortResponse.ProtoReflect.Descriptor instead.
func (*GetWarehousesShortResponse) Descriptor() ([]byte, []int) {
	return file_logistic_logistic_proto_rawDescGZIP(), []int{5}
}

func (x *GetWarehousesShortResponse) GetWarehouses() []*WarehouseShort {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

type GetWarehouseByIdParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehouseByIdParams) Reset() {
	*x = GetWarehouseByIdParams{}
	mi := &file_logistic_logistic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehouseByIdParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehouseByIdParams) ProtoMessage() {}

func (x *GetWarehouseByIdParams) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_logistic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehouseByIdParams.ProtoReflect.Descriptor instead.
func (*GetWarehouseByIdParams) Descriptor() ([]byte, []int) {
	return file_logistic_logistic_proto_rawDescGZIP(), []int{6}
}

func (x *GetWarehouseByIdParams) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateWarehouseParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWarehouseParams) Reset() {
	*x = CreateWarehouseParams{}
	mi := &file_logistic_logistic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWarehouseParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWarehouseParams) ProtoMessage() {}

func (x *CreateWarehouseParams) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_logistic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWarehouseParams.ProtoReflect.Descriptor instead.
func (*CreateWarehouseParams) Descriptor() ([]byte, []int) {
	return file_logistic_logistic_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWarehouseParams) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateWarehouseParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateWarehouseParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWarehouseParams) Reset() {
	*x = UpdateWarehouseParams{}
	mi := &file_logistic_logistic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWarehouseParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWarehouseParams) ProtoMessage() {}

func (x *UpdateWarehouseParams) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_logistic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWarehouseParams.ProtoReflect.Descriptor instead.
func (*UpdateWarehouseParams) Descriptor() ([]byte, []int) {
	return file_logistic_logistic_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateWarehouseParams) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWarehouseParams) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateWarehouseParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWarehouseParams) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DeleteWarehousesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []int32                `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWarehousesParams) Reset() {
	*x = DeleteWarehousesParams{}
	mi := &file_logistic_logistic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWarehousesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWarehousesParams) ProtoMessage() {}

func (x *DeleteWarehousesParams) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_logistic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWarehousesParams.ProtoReflect.Descriptor instead.
func (*DeleteWarehousesParams) Descriptor() ([]byte, []int) {
	return file_logistic_logistic_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteWarehousesParams) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteWarehousesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AttachedProducts []int32                `protobuf:"varint,1,rep,packed,name=attached_products,json=attachedProducts,proto3" json:"attached_products,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteWarehousesResponse) Reset() {
	*x = DeleteWarehousesResponse{}
	mi := &file_logistic_logistic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWarehousesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWarehousesResponse) ProtoMessage() {}

func (x *DeleteWarehousesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_logistic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWarehousesResponse.ProtoReflect.Descriptor instead.
func (*DeleteWarehousesResponse) Descriptor() ([]byte, []int) {
	return file_logistic_logistic_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteWarehousesResponse) GetAttachedProducts() []int32 {
	if x != nil {
		return x.AttachedProducts
	}
	return nil
}

var File_logistic_logistic_proto protoreflect.FileDescriptor

const file_logistic_logistic_proto_rawDesc = "" +
	"\n" +
	"\x17logistic/logistic.proto\x12\blogistic\"f\n" +
	"\tWarehouse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"N\n" +
	"\x0eWarehouseShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"'\n" +
	"\x13GetWarehousesParams\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\",\n" +
	"\x18GetWarehousesShortParams\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"L\n" +
	"\x15GetWarehousesResponse\x123\n" +
	"\n" +
	"warehouses\x18\x01 \x03(\v2\x13.logistic.WarehouseR\n" +
	"warehouses\"V\n" +
	"\x1aGetWarehousesShortResponse\x128\n" +
	"\n" +
	"warehouses\x18\x01 \x03(\v2\x18.logistic.WarehouseShortR\n" +
	"warehouses\"(\n" +
	"\x16GetWarehouseByIdParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"E\n" +
	"\x15CreateWarehouseParams\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"r\n" +
	"\x15UpdateWarehouseParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"(\n" +
	"\x16DeleteWarehousesParams\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x05R\x02id\"G\n" +
	"\x18DeleteWarehousesResponse\x12+\n" +
	"\x11attached_products\x18\x01 \x03(\x05R\x10attachedProducts2\xf1\x03\n" +
	"\bLogistic\x12O\n" +
	"\rGetWarehouses\x12\x1d.logistic.GetWarehousesParams\x1a\x1f.logistic.GetWarehousesResponse\x12^\n" +
	"\x12GetWarehousesShort\x12\".logistic.GetWarehousesShortParams\x1a$.logistic.GetWarehousesShortResponse\x12I\n" +
	"\x10GetWarehouseById\x12 .logistic.GetWarehouseByIdParams\x1a\x13.logistic.Warehouse\x12G\n" +
	"\x0fCreateWarehouse\x12\x1f.logistic.CreateWarehouseParams\x1a\x13.logistic.Warehouse\x12G\n" +
	"\x0fUpdateWarehouse\x12\x1f.logistic.UpdateWarehouseParams\x1a\x13.logistic.Warehouse\x12W\n" +
	"\x0fDeleteWarehouse\x12 .logistic.DeleteWarehousesParams\x1a\".logistic.DeleteWarehousesResponseB:Z8github.com/market-4-test/contract-go/logistic;logisticv1b\x06proto3"

var (
	file_logistic_logistic_proto_rawDescOnce sync.Once
	file_logistic_logistic_proto_rawDescData []byte
)

func file_logistic_logistic_proto_rawDescGZIP() []byte {
	file_logistic_logistic_proto_rawDescOnce.Do(func() {
		file_logistic_logistic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logistic_logistic_proto_rawDesc), len(file_logistic_logistic_proto_rawDesc)))
	})
	return file_logistic_logistic_proto_rawDescData
}

var file_logistic_logistic_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_logistic_logistic_proto_goTypes = []any{
	(*Warehouse)(nil),                  // 0: logistic.Warehouse
	(*WarehouseShort)(nil),             // 1: logistic.WarehouseShort
	(*GetWarehousesParams)(nil),        // 2: logistic.GetWarehousesParams
	(*GetWarehousesShortParams)(nil),   // 3: logistic.GetWarehousesShortParams
	(*GetWarehousesResponse)(nil),      // 4: logistic.GetWarehousesResponse
	(*GetWarehousesShortResponse)(nil), // 5: logistic.GetWarehousesShortResponse
	(*GetWarehouseByIdParams)(nil),     // 6: logistic.GetWarehouseByIdParams
	(*CreateWarehouseParams)(nil),      // 7: logistic.CreateWarehouseParams
	(*UpdateWarehouseParams)(nil),      // 8: logistic.UpdateWarehouseParams
	(*DeleteWarehousesParams)(nil),     // 9: logistic.DeleteWarehousesParams
	(*DeleteWarehousesResponse)(nil),   // 10: logistic.DeleteWarehousesResponse
}
var file_logistic_logistic_proto_depIdxs = []int32{
	0,  // 0: logistic.GetWarehousesResponse.warehouses:type_name -> logistic.Warehouse
	1,  // 1: logistic.GetWarehousesShortResponse.warehouses:type_name -> logistic.WarehouseShort
	2,  // 2: logistic.Logistic.GetWarehouses:input_type -> logistic.GetWarehousesParams
	3,  // 3: logistic.Logistic.GetWarehousesShort:input_type -> logistic.GetWarehousesShortParams
	6,  // 4: logistic.Logistic.GetWarehouseById:input_type -> logistic.GetWarehouseByIdParams
	7,  // 5: logistic.Logistic.CreateWarehouse:input_type -> logistic.CreateWarehouseParams
	8,  // 6: logistic.Logistic.UpdateWarehouse:input_type -> logistic.UpdateWarehouseParams
	9,  // 7: logistic.Logistic.DeleteWarehouse:input_type -> logistic.DeleteWarehousesParams
	4,  // 8: logistic.Logistic.GetWarehouses:output_type -> logistic.GetWarehousesResponse
	5,  // 9: logistic.Logistic.GetWarehousesShort:output_type -> logistic.GetWarehousesShortResponse
	0,  // 10: logistic.Logistic.GetWarehouseById:output_type -> logistic.Warehouse
	0,  // 11: logistic.Logistic.CreateWarehouse:output_type -> logistic.Warehouse
	0,  // 12: logistic.Logistic.UpdateWarehouse:output_type -> logistic.Warehouse
	10, // 13: logistic.Logistic.DeleteWarehouse:output_type -> logistic.DeleteWarehousesResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_logistic_logistic_proto_init() }
func file_logistic_logistic_proto_init() {
	if File_logistic_logistic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logistic_logistic_proto_rawDesc), len(file_logistic_logistic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logistic_logistic_proto_goTypes,
		DependencyIndexes: file_logistic_logistic_proto_depIdxs,
		MessageInfos:      file_logistic_logistic_proto_msgTypes,
	}.Build()
	File_logistic_logistic_proto = out.File
	file_logistic_logistic_proto_goTypes = nil
	file_logistic_logistic_proto_depIdxs = nil
}
